"""Reference implementation. No runtime consumer. Not a gate."""

from .catalog import PackageCatalog, PackageValidationError, load_package
from .host_profiles import (
    ConformanceStatus,
    EvidenceLevel,
    HostCapability,
    HostCapabilityProfile,
    load_builtin_host_profile,
    load_builtin_host_profiles,
)
from .models import (
    AgentManifest,
    CatalogSnapshot,
    ComponentKind,
    ComponentManifest,
    ComponentRef,
    FileRecord,
    LicenseStatus,
    LoadedPackage,
    PackageManifest,
    PackagePin,
    SkillManifest,
    ToolManifest,
    TrustState,
    WorkflowManifest,
    WorkflowTransition,
    canonical_json_bytes,
    content_digest,
)
from .ooda import (
    OODAContractValidation,
    OODAPhase,
    OODAState,
    OODAStatus,
    OODATerminalRecord,
    OODATransition,
    validate_ooda_contract,
)

__all__ = [
    "AgentManifest",
    "CatalogSnapshot",
    "ComponentKind",
    "ComponentManifest",
    "ComponentRef",
    "ConformanceStatus",
    "EvidenceLevel",
    "FileRecord",
    "HostCapability",
    "HostCapabilityProfile",
    "LicenseStatus",
    "LoadedPackage",
    "OODAContractValidation",
    "OODAPhase",
    "OODAState",
    "OODAStatus",
    "OODATerminalRecord",
    "OODATransition",
    "PackageCatalog",
    "PackageManifest",
    "PackagePin",
    "PackageValidationError",
    "SkillManifest",
    "ToolManifest",
    "TrustState",
    "WorkflowManifest",
    "WorkflowTransition",
    "canonical_json_bytes",
    "content_digest",
    "load_package",
    "load_builtin_host_profile",
    "load_builtin_host_profiles",
    "validate_ooda_contract",
]
