"""Additive, repository-neutral primitives for the Verifiable Hive Kernel."""

from .canonical import canonical_bytes, canonical_digest
from .context import (
    CompiledContext,
    ContextCompiler,
    ContextManifestStore,
    ContextRequest,
    HotContextItem,
    manifest_digest,
)
from .contracts import (
    Budget,
    Candidate,
    CandidateState,
    ConstraintEnvelope,
    ContextManifest,
    EffectIntent,
    EffectReceipt,
    EvaluationPlan,
    EvaluationResult,
    EvaluationState,
    ExecutionLease,
    HistoricalEvidenceReference,
    LeaseState,
    MemoryRecord,
    MemoryState,
    MissionCharter,
    MissionState,
    RoleResult,
    TechnicalCloseoutReport,
    TechnicalCloseoutState,
    WorkItem,
    WorkState,
    normalize_portable_path,
)
from .memory import (
    SENSITIVITY_LEVELS,
    ConsolidationPolicy,
    MemoryAccess,
    MemoryArtifact,
    MemoryArtifactStore,
    MemoryCatalog,
    MemoryCatalogStore,
    MemoryClass,
    MemoryConflict,
    MemoryDenied,
    MemoryEntry,
    MemoryLifecycleEvent,
    MemorySnapshot,
    RankedMemory,
    RetrievalRequest,
    ScoreTerms,
    estimate_tokens,
    normalize_terms,
)
from .objectives import ObjectiveGraph, PlanLimits, paths_overlap
from .planner import (
    DeterministicFixturePlanner,
    FixturePlan,
    graph_from_events,
    persist_plan,
)
from .roles import (
    KERNEL_IMPLEMENTED_ROLES,
    RoleCapabilities,
    RoleHandler,
    RoleInvocation,
    RoleProtocolError,
    append_role_result,
    next_role,
    result_digest,
    role_capabilities,
    role_allows_action,
    role_prompt,
)
from .role_runtime import RoleCapabilityDenied, RoleRuntime
from .verification import (
    ExactCandidateVerificationError,
    TreeSnapshot,
    VerificationOutcome,
    accept_verified_work,
    create_evaluation_plan,
    evaluation_plan_digest,
    evaluation_result_digest,
    seal_evaluation_plan,
    snapshot_tree,
    verify_bundle,
    verify_exact_candidate,
)

_CLOSEOUT_EXPORTS = frozenset(
    {
        "TechnicalCloseoutError",
        "declare_closeout_obligations",
        "derive_technical_closeout",
        "integrate_verified_work",
        "record_evaluation_bundle",
        "technical_closeout_digest",
    }
)


def __getattr__(name: str):
    if name in _CLOSEOUT_EXPORTS:
        from . import closeout

        return getattr(closeout, name)
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")


__all__ = (
    "Budget",
    "TechnicalCloseoutError",
    "Candidate",
    "CandidateState",
    "ConsolidationPolicy",
    "CompiledContext",
    "ConstraintEnvelope",
    "ContextCompiler",
    "ContextManifest",
    "ContextManifestStore",
    "ContextRequest",
    "EffectIntent",
    "EffectReceipt",
    "EvaluationPlan",
    "EvaluationResult",
    "EvaluationState",
    "ExecutionLease",
    "LeaseState",
    "MemoryRecord",
    "MemoryAccess",
    "MemoryArtifact",
    "MemoryArtifactStore",
    "MemoryCatalog",
    "MemoryCatalogStore",
    "MemoryClass",
    "MemoryConflict",
    "MemoryDenied",
    "MemoryEntry",
    "MemoryLifecycleEvent",
    "MemorySnapshot",
    "MemoryState",
    "ObjectiveGraph",
    "PlanLimits",
    "RankedMemory",
    "RetrievalRequest",
    "ScoreTerms",
    "SENSITIVITY_LEVELS",
    "MissionCharter",
    "MissionState",
    "HistoricalEvidenceReference",
    "RoleResult",
    "TechnicalCloseoutReport",
    "TechnicalCloseoutState",
    "WorkItem",
    "WorkState",
    "canonical_bytes",
    "canonical_digest",
    "declare_closeout_obligations",
    "derive_technical_closeout",
    "DeterministicFixturePlanner",
    "FixturePlan",
    "HotContextItem",
    "graph_from_events",
    "integrate_verified_work",
    "estimate_tokens",
    "manifest_digest",
    "normalize_terms",
    "normalize_portable_path",
    "paths_overlap",
    "persist_plan",
    "KERNEL_IMPLEMENTED_ROLES",
    "RoleCapabilities",
    "RoleHandler",
    "RoleInvocation",
    "RoleProtocolError",
    "append_role_result",
    "result_digest",
    "role_capabilities",
    "role_allows_action",
    "role_prompt",
    "RoleCapabilityDenied",
    "RoleRuntime",
    "record_evaluation_bundle",
    "technical_closeout_digest",
    "next_role",
    "ExactCandidateVerificationError",
    "TreeSnapshot",
    "VerificationOutcome",
    "accept_verified_work",
    "create_evaluation_plan",
    "evaluation_plan_digest",
    "evaluation_result_digest",
    "seal_evaluation_plan",
    "snapshot_tree",
    "verify_bundle",
    "verify_exact_candidate",
)
