"""Additive, repository-neutral primitives for the Verifiable Hive Kernel."""

from .canonical import canonical_bytes, canonical_digest
from .context import (
    CompiledContext,
    ContextCompiler,
    ContextManifestStore,
    ContextRequest,
    HotContextItem,
    manifest_digest,
)
from .contracts import (
    Budget,
    Candidate,
    CandidateState,
    ConstraintEnvelope,
    ContextManifest,
    EffectIntent,
    EffectReceipt,
    EvaluationPlan,
    EvaluationResult,
    EvaluationState,
    ExecutionLease,
    LeaseState,
    MemoryRecord,
    MemoryState,
    MissionCharter,
    MissionState,
    RoleResult,
    WorkItem,
    WorkState,
    normalize_portable_path,
)
from .memory import (
    MemoryAccess,
    MemoryArtifact,
    MemoryArtifactStore,
    MemoryCatalog,
    MemoryConflict,
    MemoryDenied,
    MemoryEntry,
    MemoryLifecycleEvent,
    RankedMemory,
    RetrievalRequest,
    ScoreTerms,
    estimate_tokens,
    normalize_terms,
)
from .objectives import ObjectiveGraph, PlanLimits, paths_overlap
from .planner import (
    DeterministicFixturePlanner,
    FixturePlan,
    graph_from_events,
    persist_plan,
)

__all__ = (
    "Budget",
    "Candidate",
    "CandidateState",
    "CompiledContext",
    "ConstraintEnvelope",
    "ContextCompiler",
    "ContextManifest",
    "ContextManifestStore",
    "ContextRequest",
    "EffectIntent",
    "EffectReceipt",
    "EvaluationPlan",
    "EvaluationResult",
    "EvaluationState",
    "ExecutionLease",
    "LeaseState",
    "MemoryRecord",
    "MemoryAccess",
    "MemoryArtifact",
    "MemoryArtifactStore",
    "MemoryCatalog",
    "MemoryConflict",
    "MemoryDenied",
    "MemoryEntry",
    "MemoryLifecycleEvent",
    "MemoryState",
    "ObjectiveGraph",
    "PlanLimits",
    "RankedMemory",
    "RetrievalRequest",
    "ScoreTerms",
    "MissionCharter",
    "MissionState",
    "RoleResult",
    "WorkItem",
    "WorkState",
    "canonical_bytes",
    "canonical_digest",
    "DeterministicFixturePlanner",
    "FixturePlan",
    "HotContextItem",
    "graph_from_events",
    "estimate_tokens",
    "manifest_digest",
    "normalize_terms",
    "normalize_portable_path",
    "paths_overlap",
    "persist_plan",
)
