"""Immutable no-code VTC court contracts."""
from __future__ import annotations

EVALUATED_COMMIT = "b789b68e7d6a741e0b85a3ac33cbce846e1e32c9"
EVALUATED_TREE = "b909b7b7e374bff22912059387ef0fe639498af6"
REJECTED_TUPLES = (("20e26e3c53d41ec4093b23f0957766cd0cbdab70", "f454db6d64120c946ae6700bcf4b4b6ea1bef26c"), ("20e26e3c53d41ec4093b23f0957766cd0cbdab70", "4f20bd2"))
DAG_DIR = "docs/execution/dags/validation-target-composition-v1"
EVIDENCE = "evidence/performance/validation-target-composition-v1"
OPENING = "evidence/courts/CASE-VALIDATION-TARGET-COMPOSITION-OPENING.json"
FPCR_JUDGE = "evidence/courts/CASE-FIXTURE-PREREQUISITE-CAUSALITY-RESEAL-QUALIFICATION.json"
ADVERSE = ["evidence/courts/CASE-FIXTURE-PREREQUISITE-OPENING.json", "evidence/performance/fixture-prerequisite-v1/causality.json", "evidence/courts/CASE-FIXTURE-PREREQUISITE-CAUSALITY-APPEAL-OPENING.json", "evidence/performance/fixture-prerequisite-causality-appeal-v1/discovery-analysis.json", FPCR_JUDGE, "evidence/performance/fixture-prerequisite-causality-reseal-v2/discovery-analysis.json", "evidence/performance/fixture-prerequisite-causality-reseal-v2/execution.json", "evidence/performance/fixture-prerequisite-causality-reseal-v2/execution-transcript.json", "evidence/performance/fixture-prerequisite-causality-reseal-v2/cross-examination.json", "evidence/performance/fixture-prerequisite-causality-reseal-v2/integration.json", "evidence/courts/CASE-DOCTOR-PERFORMANCE-PROMOTION.json"]
COMMON_FORBIDDEN = [".autopilot/plan.json", ".autopilot/bin/**", ".autopilot/tests/**", "tests/**", "src/**", "pyproject.toml", "docs/execution/dags/fixture-prerequisite-v1/**", "docs/execution/dags/fixture-prerequisite-causality-appeal-v1/**", "docs/execution/dags/fixture-prerequisite-causality-reseal-v2/**", "docs/execution/dags/git-commit-observation-v1/**", "docs/execution/dags/doctor-performance-v1/**", "evidence/performance/doctor-performance-v1/**", "refs/heads/main", "refs/remotes/origin/**"]

def node(ident, title, objective, rationale, dependencies, role, seat, inputs, outputs, read_scope, tests, parallel, locks, importance):
    return {"id":ident,"title":title,"objective":objective,"rationale":rationale,"dependencies":dependencies,"primary_role":role,"court_seat":seat,"consulted_roles":["curator","steward"],"required_inputs":inputs,"expected_outputs":outputs,"read_scope":read_scope,"write_scope":outputs,"required_tests":tests,"acceptance_criteria":["Bind only the exact b789/b909 source tuple and reject both historic bad tuples.","Write only the declared evidence or contract artifact.","No CI rerun, candidate execution, implementation, plan, main, or remote effect occurs."],"parallel_safe":parallel,"semantic_locks":locks,"critical_path_importance":importance,"stopping_condition":"Required checks pass, the sole declared artifact is retained, and no out-of-scope path changed.","rollback":"Revert only this node's retained contract or evidence commit; never delete prior adverse evidence."}

# The Clerk owns this evidence root before the two parallel evidence writers are
# released.  It is a declared scaffold surface, not an additional committed file.
SEAL = [f"{DAG_DIR}/.gitignore",f"{DAG_DIR}/README.md",f"{DAG_DIR}/specs.py",f"{DAG_DIR}/generate_plan.py",f"{DAG_DIR}/verify_plan.py",f"{DAG_DIR}/manifest.json",OPENING,f"{EVIDENCE}/"]
SPECS = [
 node("VTC-SEAL-000", "Seal validation-target composition court", "As Clerk, seal a five-node no-code court before any observation.", "FPCR authorizes a separate court opening only.", [], "orchestrator", "clerk-distinct", ["AGENTS.md", "docs/execution/DAG_AUTHORING_STANDARD.md", FPCR_JUDGE, *ADVERSE], SEAL, ["AGENTS.md", "docs/execution/DAG_AUTHORING_STANDARD.md", FPCR_JUDGE, *ADVERSE], [f"python {DAG_DIR}/verify_plan.py"], False, ["contract:vtc-v1"], 100),
 node("VTC-DISCOVERY-010", "Inventory validation-target composition", "As independent Explorer, classify and reconcile 1,059 discovery IDs against 1,050 historical executed tests without rerunning CI.", "The nine-test delta is unresolved FPCR evidence, not inherited truth.", ["VTC-SEAL-000"], "explorer", "independent-explorer", [f"{DAG_DIR}/specs.py", *ADVERSE], [f"{EVIDENCE}/discovery-analysis.json"], ["tests/", "pyproject.toml", *ADVERSE], [f"python {DAG_DIR}/verify_plan.py"], True, ["evidence:vtc-discovery"], 95),
 node("VTC-CROSS-020", "Cross-examine candidate composition", "As separate Cross-Examiner, challenge source identity, inventory classification, and the separation of fixture and GCO API components.", "Neither component establishes causal sufficiency in isolation.", ["VTC-SEAL-000"], "curator", "cross-examiner-distinct", [f"{DAG_DIR}/specs.py", *ADVERSE], [f"{EVIDENCE}/cross-examination.json"], ["tests/", "pyproject.toml", *ADVERSE], [f"python {DAG_DIR}/verify_plan.py"], True, ["evidence:vtc-cross"], 90),
 node("VTC-INTEGRATE-030", "Integrate composition evidence", "As Integrator, reconcile independent discovery and cross-examination into a no-code applicability record.", "A court needs contradiction handling before judgment.", ["VTC-DISCOVERY-010", "VTC-CROSS-020"], "integrator", "integrator-distinct", [f"{EVIDENCE}/discovery-analysis.json", f"{EVIDENCE}/cross-examination.json", *ADVERSE], [f"{EVIDENCE}/integration.json"], [f"{EVIDENCE}/discovery-analysis.json", f"{EVIDENCE}/cross-examination.json", *ADVERSE], [f"python {DAG_DIR}/verify_plan.py"], False, ["integration:vtc"], 80),
 node("VTC-JUDGE-040", "Judge validation-target composition", "As a Judge distinct from all prior VTC roles, decide only whether a separate implementation proposal may be opened.", "FPCR requires zero unresolved material findings before any later proposal.", ["VTC-INTEGRATE-030"], "orchestrator", "judge-distinct-from-all-vtc-roles", [f"{EVIDENCE}/integration.json", f"{EVIDENCE}/cross-examination.json", FPCR_JUDGE], ["evidence/courts/CASE-VALIDATION-TARGET-COMPOSITION-QUALIFICATION.json"], [f"{EVIDENCE}/integration.json", f"{EVIDENCE}/cross-examination.json", FPCR_JUDGE], [f"python {DAG_DIR}/verify_plan.py"], False, ["court:vtc-verdict"], 70),
]
