"""Node contracts for the knowledge-projection implementation DAG.

The data in this module describes future work. Importing it performs no repository,
network, Obsidian, registry, or publication effect.
"""

from __future__ import annotations


def node(
    node_id: str,
    title: str,
    objective: str,
    dependencies: list[str],
    primary_role: str,
    consulted_roles: list[str],
    importance: int,
    parallel_safe: bool,
    semantic_locks: list[str],
    read_scope: list[str],
    write_scope: list[str],
    required_tests: list[str],
    acceptance_criteria: list[str],
    rationale: str,
    required_inputs: list[str] | None = None,
    expected_outputs: list[str] | None = None,
) -> dict[str, object]:
    return {
        "id": node_id,
        "title": title,
        "objective": objective,
        "dependencies": dependencies,
        "primary_role": primary_role,
        "consulted_roles": consulted_roles,
        "critical_path_importance": importance,
        "parallel_safe": parallel_safe,
        "semantic_locks": semantic_locks,
        "read_scope": read_scope,
        "write_scope": write_scope,
        "required_tests": required_tests,
        "required_inputs": list(required_inputs or []),
        "expected_outputs": list(expected_outputs or write_scope),
        "acceptance_criteria": acceptance_criteria,
        "rationale": rationale,
        "implementation_status": "not_started",
    }


SPECS = [
    node(
        "BASELINE-000",
        "Seal the tournament baseline",
        "Verify the exact main commit, source register, tournament judgment, DAG sources, and the prohibition on changing the sealed Autopilot plan.",
        [],
        "orchestrator",
        ["explorer", "curator"],
        100,
        False,
        ["gate:knowledge-baseline"],
        [
            "AGENTS.md",
            "docs/architecture/HARDENED_VISION_CONTRACT.md",
            "docs/plan/knowledge-projection-tournament-2026-08-13/",
            "docs/execution/dags/knowledge-projection-v1/",
            ".autopilot/plan.json",
        ],
        [
            ".autopilot/state/knowledge-projection-v1.json",
            "evidence/knowledge-projection/baseline.json",
        ],
        [
            "python docs/execution/dags/knowledge-projection-v1/verify_plan.py --write",
            "python .autopilot/bin/autopilot.py --repo-root . dag-lint --plan .autopilot/state/knowledge-projection-v1.json --strict --json",
            "python .autopilot/bin/autopilot.py --repo-root . doctor --json",
        ],
        [
            "The candidate descends from baseline commit a93df2632f259f4b63f7a4f27eb0b163b5a47204 with retained ancestry.",
            "The tournament bundle, authoring standard, generated plan, and every node contract reproduce their sealed digests.",
            "The record distinguishes implemented main code, an unmerged historical prototype, proposals, and deferred external evidence.",
            ".autopilot/plan.json is byte-identical to the baseline and no worker can edit this overlay.",
        ],
        "A new program cannot inherit completion or safety claims from the earlier 39-node DAG or from a divergent prototype branch.",
    ),
    node(
        "SOURCE-010",
        "Reconcile sources and implementation truth",
        "Produce a point-in-time inventory of canonical stores, graph objects, code-backed capabilities, unmerged prototype components, and open source-ingestion obligations.",
        ["BASELINE-000"],
        "explorer",
        ["architect", "curator", "integrator"],
        99,
        False,
        ["evidence:knowledge-source-inventory"],
        [
            "docs/plan/knowledge-projection-tournament-2026-08-13/SOURCE_REGISTER.md",
            "docs/NEXT_SESSION_HANDOFF_OBSIDIAN_AGENT_REDESIGN.md",
            "src/hive_mind_os/brain_kernel/",
            "src/hive_mind_os/projection.py",
            ".autopilot/bin/learning.py",
            ".autopilot/lessons/README.md",
        ],
        [
            "evidence/knowledge-projection/source-inventory.json",
            "evidence/knowledge-projection/source-obligations.json",
        ],
        [
            "python -m unittest tests.test_brain_kernel_store tests.test_brain_kernel_memory_context tests.test_hive_cortex_learning tests.test_hive_cortex_court -v",
            "python docs/execution/dags/knowledge-projection-v1/verify_plan.py",
        ],
        [
            "Every store that can hold missions, work, courts, memory, lessons, champion history, or Autopilot lessons has one recorded authority status.",
            "Every required graph record type is classified as implemented, partial, prototype-only, proposed, or blocked with exact source evidence.",
            "Official Obsidian behavior and any other unavailable external source remain explicit evidence obligations rather than inferred facts.",
            "The inventory identifies cross-repository detail already retained by .autopilot/lessons and does not copy those details into a shared plan artifact.",
        ],
        "Canonical ownership must be known before a projector can truthfully merge records from several present stores.",
    ),
    node(
        "AUTHORITY-020",
        "Close authority-envelope expansion paths",
        "Bind authority digests to content and enforce narrowing across actions, denies, paths, network, data, secrets, gates, identity, expiry, policy, and every budget dimension.",
        ["SOURCE-010"],
        "architect",
        ["curator", "builder", "integrator"],
        98,
        True,
        ["iface:authority-envelope", "policy:capability-narrowing"],
        [
            "src/hive_mind_os/brain_kernel/authority.py",
            "src/hive_mind_os/brain_kernel/contracts.py",
            "src/hive_mind_os/brain_kernel/effects.py",
            "src/hive_mind_os/brain_kernel/effect_outbox.py",
            "tests/test_brain_kernel_authority.py",
            "tests/test_hive_cortex_effects.py",
            "tests/hive_cortex/test_no_cheating.py",
            "docs/execution/A5_GOVERNED_FULL_READINESS.md",
        ],
        [
            "src/hive_mind_os/brain_kernel/authority.py",
            "src/hive_mind_os/brain_kernel/contracts.py",
            "src/hive_mind_os/brain_kernel/effects.py",
            "src/hive_mind_os/brain_kernel/effect_outbox.py",
            "tests/test_brain_kernel_authority.py",
            "tests/test_hive_cortex_effects.py",
            "tests/test_knowledge_authority_prerequisites.py",
            "docs/execution/KNOWLEDGE_AUTHORITY_PREREQUISITES.md",
        ],
        ["python -m unittest tests.test_knowledge_authority_prerequisites tests.test_brain_kernel_authority tests.test_hive_cortex_effects -v"],
        [
            "All authority documents recompute and compare their canonical digest before registration or use.",
            "Registration rejects digest collisions, cross-mission/work substitution, stale policy, invalid expiry, and any wider child envelope.",
            "Narrowing covers all budget fields, data scopes, secret scopes, human gates, denied actions, network destinations, and path-bearing actions.",
            "The actual effect boundary and outbox require registry-backed token validation, canonical envelope-digest recomputation, expiry and revocation checks at use time, mission/work binding, and collision rejection.",
            "Private projection and shared release use separate least-authority grants; neither grant implies the other.",
        ],
        "The cross-examination demonstrated that current narrowing can expand sensitive scopes and budgets, so no release capability may rely on it unchanged.",
        required_inputs=[
            "evidence/knowledge-projection/source-inventory.json",
            "evidence/knowledge-projection/source-obligations.json",
        ],
    ),
    node(
        "LEARNING-030",
        "Harden lesson and challenger admission",
        "Make lessons content-bound, time-valid, provenance-resolved, structured, inert on import, and unable to inject shared prose into a champion or prompt challenger.",
        ["SOURCE-010"],
        "optimizer",
        ["curator", "architect", "builder"],
        97,
        True,
        ["iface:lesson-admission", "gate:challenger-intake"],
        [
            "src/hive_mind_os/brain_kernel/learning_runtime.py",
            "src/hive_mind_os/brain_kernel/challengers.py",
            "src/hive_mind_os/brain_kernel/evaluation_runtime.py",
            "src/hive_mind_os/brain_kernel/promotion.py",
            ".autopilot/bin/learning.py",
            ".autopilot/lessons/README.md",
            "docs/execution/LEARNING_POISONING_RESULTS.md",
        ],
        [
            ".autopilot/bin/learning.py",
            ".autopilot/learning-release-policy.json",
            ".autopilot/learning-release-policy.schema.json",
            ".autopilot/lessons/README.md",
            ".autopilot/tests/test_learning_privacy.py",
            "src/hive_mind_os/brain_kernel/learning_runtime.py",
            "src/hive_mind_os/brain_kernel/challengers.py",
            "tests/test_knowledge_learning_intake.py",
            "docs/execution/KNOWLEDGE_LEARNING_INTAKE.md",
        ],
        [
            "python -m unittest discover -s .autopilot/tests -p 'test_learning_privacy.py' -v",
            "python -m unittest tests.test_knowledge_learning_intake tests.test_hive_cortex_learning tests.test_hive_cortex_challengers -v",
        ],
        [
            "Lesson identifiers and digests derive from canonical content and all provenance references resolve to admitted evidence.",
            "Status never defaults to accepted; expiry is parsed and current; conflicts, dissent, and counterexamples are retained.",
            "Imported or shared lessons remain typed inert candidates and cannot concatenate free text into live prompts.",
            "A local challenger still requires locally generated content, held-out evaluation, independent court judgment, and rollback.",
            "Existing committed Autopilot lessons are inventoried and quarantined from export by default without rewriting history; new instance details cannot be copied or committed across repositories without an approved release receipt.",
            "Any discovered real exposure creates a separate takedown or history-remediation case and receipt rather than silent deletion.",
        ],
        "A shared registry would otherwise become a direct poisoning and prompt-injection path into champion/challenger generation.",
        required_inputs=[
            "evidence/knowledge-projection/source-inventory.json",
            "evidence/knowledge-projection/source-obligations.json",
        ],
    ),
    node(
        "SCAFFOLD-040",
        "Own the knowledge package scaffolds",
        "Create the single owned package, schema, test, fixture, and execution-document scaffolds used by all later knowledge nodes.",
        ["SOURCE-010"],
        "architect",
        ["builder", "integrator", "steward"],
        96,
        False,
        ["scaffold:knowledge-package"],
        ["pyproject.toml", "src/hive_mind_os/brain_kernel/__init__.py", "tests/__init__.py"],
        [
            "src/hive_mind_os/knowledge/__init__.py",
            "src/hive_mind_os/knowledge/schemas/.gitkeep",
            "tests/knowledge/__init__.py",
            "tests/knowledge/conftest.py",
            "tests/fixtures/knowledge/.gitkeep",
            "docs/execution/knowledge/README.md",
        ],
        ["python -m unittest tests.knowledge -v"],
        [
            "Exactly one node owns every new shared directory marker and no later node may recreate or replace it.",
            "The package exports no runtime authority or implicit singleton.",
            "The README states the canonical-store, projection, private-vault, and shared-release boundaries.",
        ],
        "The DAG authoring standard requires a single prior owner for scaffolds used by parallel nodes.",
    ),
    node(
        "CLASSIFY-050",
        "Establish the classification and disclosure policy",
        "Implement deterministic sensitivity, proprietary, personal-data, secret, license, provenance, publishability, retention, and tenant classifications with unknown values denied.",
        ["AUTHORITY-020", "SCAFFOLD-040"],
        "curator",
        ["architect", "integrator", "steward"],
        95,
        True,
        ["policy:knowledge-classification"],
        [
            "src/hive_mind_os/brain_kernel/memory.py",
            "src/hive_mind_os/courtroom.py",
            "docs/architecture/HUMAN_AUTHORITY_GATES.md",
            "docs/plan/knowledge-projection-tournament-2026-08-13/ARCHITECTURE_DECISION.md",
        ],
        [
            "src/hive_mind_os/knowledge/classification.py",
            "src/hive_mind_os/knowledge/schemas/classification-v1.schema.json",
            "tests/knowledge/test_classification.py",
            "docs/execution/knowledge/CLASSIFICATION.md",
        ],
        ["python -m unittest tests.knowledge.test_classification -v"],
        [
            "Classification is structured and independent of storage location, filename, Git ignore state, and a single regex scan.",
            "Unknown sensitivity, ownership, license, provenance, tenant, de-identification, or publishability denies shared release.",
            "Synthetic tests cover secrets, private paths and URIs, customer identifiers, source fragments, prompts, encoded content, proprietary markers, and linkage disclosures.",
            "The policy distinguishes private retention from shared-release eligibility and records every decision reason.",
        ],
        "Privacy and IP safety require allowlisted release semantics; removing recognized bad strings from a private object is not a release proof.",
    ),
    node(
        "IDENTITY-100",
        "Define repository-neutral knowledge identities",
        "Define stable tenant, project-lineage, repository-instance, subject-commit, controller, record, and typed-edge contracts without exposing raw remotes or local paths.",
        ["AUTHORITY-020", "SCAFFOLD-040"],
        "integrator",
        ["architect", "explorer", "curator"],
        94,
        True,
        ["schema:knowledge-identity", "schema:knowledge-record"],
        [
            "src/hive_mind_os/autopilot_workflow.py",
            "src/hive_mind_os/brain_kernel/contracts.py",
            "src/hive_mind_os/brain_kernel/canonical.py",
            "docs/NEXT_SESSION_HANDOFF_OBSIDIAN_AGENT_REDESIGN.md",
        ],
        [
            "src/hive_mind_os/knowledge/identity.py",
            "src/hive_mind_os/knowledge/records.py",
            "src/hive_mind_os/knowledge/schemas/knowledge-record-v1.schema.json",
            "src/hive_mind_os/knowledge/schemas/repository-identity-v1.schema.json",
            "tests/knowledge/test_identity.py",
            "tests/knowledge/test_records.py",
            "docs/execution/knowledge/RECORD_MODEL.md",
        ],
        [
            "python -m unittest tests.knowledge.test_identity -v",
            "python -m unittest tests.knowledge.test_records -v",
        ],
        [
            "Every record has a versioned schema, stable opaque ID, content digest, tenant/repository/commit boundary, provenance, classification, actor, timestamps, and immutable payload reference.",
            "Public identities are release-scoped pseudonyms and cannot be dictionary-matched from a remote URL or absolute path.",
            "Typed edges have stable IDs, allowed endpoint kinds, evidence, actor, time, and direction; unknown kinds fail closed.",
            "Rename, clone reconciliation, fork separation, case folding, and Unicode normalization have deterministic tests.",
        ],
        "Portable identity is required before private projection, cross-repository federation, or safe de-identification can be evaluated.",
    ),
    node(
        "IDEA-110",
        "Model stable ideas and immutable passes",
        "Define Idea, IdeaEncounter, IdeaPass, relationship, transition, remand, appeal, reversal, and re-entry contracts as an append-only time-expanded graph.",
        ["IDENTITY-100", "LEARNING-030"],
        "explorer",
        ["architect", "optimizer", "orchestrator", "curator"],
        93,
        True,
        ["schema:idea-lifecycle"],
        [
            "src/hive_mind_os/brain_kernel/objectives.py",
            "src/hive_mind_os/brain_kernel/planner.py",
            "src/hive_mind_os/brain_kernel/reconciler.py",
            "src/hive_mind_os/brain_kernel/court_runtime.py",
            "docs/NEXT_SESSION_HANDOFF_OBSIDIAN_AGENT_REDESIGN.md",
        ],
        [
            "src/hive_mind_os/knowledge/ideas.py",
            "src/hive_mind_os/knowledge/schemas/idea-v1.schema.json",
            "src/hive_mind_os/knowledge/schemas/idea-pass-v1.schema.json",
            "src/hive_mind_os/knowledge/schemas/reentry-v1.schema.json",
            "tests/knowledge/test_ideas.py",
            "docs/execution/knowledge/IDEA_LIFECYCLE.md",
        ],
        ["python -m unittest tests.knowledge.test_ideas -v"],
        [
            "An idea retains one stable ID while every consideration pass has a unique immutable ID and ordinal.",
            "New evidence, deferred triggers, appeals, failed implementation, verification failure, regression, incident, and resolved risk may create a successor pass without rewriting prior conclusions.",
            "Every backward semantic edge records source gate, destination stage, exact reason, evidence, actor/role, prior pass, and successor pass/work.",
            "The persisted dependency graph remains acyclic; repeated conceptual loops are represented by later nodes and cross-time relation edges.",
            "Duplicates, refinements, variants, reinforcement, contradictions, complements, and false-merge appeals are retained rather than discarded.",
        ],
        "Literal DAG cycles would break scheduling and point-in-time replay; immutable later passes preserve both repeated ideation and acyclic execution.",
    ),
    node(
        "COVERAGE-120",
        "Define complete lifecycle and role coverage",
        "Map every material source, claim, role episode, court seat, gate, work transition, candidate, verification, delivery, outcome, incident, authority, lesson, champion, and challenger to required record and edge types.",
        ["IDENTITY-100"],
        "orchestrator",
        ["explorer", "architect", "builder", "curator", "integrator", "steward", "optimizer"],
        92,
        True,
        ["schema:knowledge-coverage"],
        [
            "AGENTS.md",
            "docs/architecture/HARDENED_VISION_CONTRACT.md",
            "src/hive_mind_os/brain_kernel/roles.py",
            "src/hive_mind_os/brain_kernel/court_runtime.py",
            "docs/execution/ROLE_WIRING_AUDIT.md",
        ],
        [
            "src/hive_mind_os/knowledge/coverage.py",
            "src/hive_mind_os/knowledge/schemas/coverage-report-v1.schema.json",
            "src/hive_mind_os/knowledge/schemas/trace-edge-v1.schema.json",
            "tests/knowledge/test_coverage.py",
            "docs/execution/knowledge/COVERAGE_MATRIX.md",
        ],
        ["python -m unittest tests.knowledge.test_coverage -v"],
        [
            "All eight specialist roles and Clerk, Advocate, Cross-Examiner, Expert Witness, Judge, and Appeals Judge are separately attributable.",
            "Role evidence distinguishes declared, fixture, model turn, real repository read, real effect, and independently verified maturity.",
            "Every required record is present or carries an explicit evidence-backed not-applicable disposition.",
            "A complete trace can be required from source and atomic claim through decision, work, deliverable, outcome, lesson, and later re-entry.",
        ],
        "Graph presence must not misrepresent declarative role wiring or fixture behavior as completed autonomy.",
        required_inputs=[
            "evidence/knowledge-projection/source-inventory.json",
            "evidence/knowledge-projection/source-obligations.json",
        ],
    ),
    node(
        "PROJECT-CONTRACT-130",
        "Freeze projection transaction contracts",
        "Define deterministic cursor, exact manifest, staging, expected-prior digest, conflict, tombstone, transaction, and receipt contracts for a generated private knowledge view.",
        ["CLASSIFY-050", "IDENTITY-100"],
        "integrator",
        ["architect", "steward", "curator"],
        91,
        True,
        ["schema:projection-transaction"],
        [
            "src/hive_mind_os/projection.py",
            "docs/NEXT_SESSION_HANDOFF_OBSIDIAN_AGENT_REDESIGN.md",
            "docs/plan/knowledge-projection-tournament-2026-08-13/SOURCE_REGISTER.md",
        ],
        [
            "src/hive_mind_os/knowledge/projection_contracts.py",
            "src/hive_mind_os/knowledge/schemas/projection-manifest-v1.schema.json",
            "src/hive_mind_os/knowledge/schemas/projection-receipt-v1.schema.json",
            "src/hive_mind_os/knowledge/schemas/projection-conflict-v1.schema.json",
            "tests/knowledge/test_projection_contracts.py",
            "docs/execution/knowledge/PROJECTION_PROTOCOL.md",
        ],
        ["python -m unittest tests.knowledge.test_projection_contracts -v"],
        [
            "A projection binds canonical source head, schema/renderer versions, cursor, complete file manifest, prior projection, classifications, and transaction identity.",
            "Generated filenames derive from opaque stable IDs; titles and paths never become canonical identity.",
            "Human edits, unexpected files, stale generated files, missing files, and source drift produce retained conflicts or tombstones rather than silent overwrite or deletion.",
            "No schema requires Obsidian, an account, Sync, a plugin, or a network connection.",
        ],
        "The current JSON/HTML projection performs direct writes and cannot support a safe private knowledge vault without a stronger protocol.",
    ),
    node(
        "RELEASE-CONTRACT-140",
        "Freeze safe shared-learning contracts",
        "Define allowlisted abstraction candidates, independent release decisions, local registry entries, counterexamples, applicability, revocation, and tombstone contracts.",
        ["CLASSIFY-050", "IDENTITY-100", "LEARNING-030"],
        "architect",
        ["curator", "integrator", "optimizer"],
        90,
        True,
        ["schema:shared-learning-release"],
        [
            ".autopilot/bin/learning.py",
            ".autopilot/lessons/README.md",
            "src/hive_mind_os/brain_kernel/learning_runtime.py",
            "src/hive_mind_os/repository_learning.py",
            "docs/plan/knowledge-projection-tournament-2026-08-13/ARCHITECTURE_DECISION.md",
        ],
        [
            "src/hive_mind_os/knowledge/release_contracts.py",
            "src/hive_mind_os/knowledge/schemas/shared-learning-candidate-v1.schema.json",
            "src/hive_mind_os/knowledge/schemas/shared-learning-record-v1.schema.json",
            "src/hive_mind_os/knowledge/schemas/release-decision-v1.schema.json",
            "tests/knowledge/test_release_contracts.py",
            "docs/execution/knowledge/SHARED_LEARNING_CONTRACT.md",
        ],
        ["python -m unittest tests.knowledge.test_release_contracts -v"],
        [
            "The shared schema can express only abstract mechanism, constraints, applicability, outcome summary, counterexamples, and non-reversible evidence digests.",
            "Raw source, patch, prompt, log, transcript, URI, branch, path, customer, credential, proprietary identifier, repository name, and private link topology have no fields in the shared record.",
            "Every candidate records builder, independent Curator, distinct Judge, classification/license/provenance results, expiration, revocation, and local reproduction requirements.",
            "Remote transport and automatic release remain outside this contract and outside the DAG's authority.",
        ],
        "A structurally allowlisted record is safer than copying a private object and attempting to redact unknown sensitive fields.",
    ),
    node(
        "ADVERSARY-150",
        "Build the adversarial disclosure corpus",
        "Create synthetic, license-clean fixtures for secret, privacy, proprietary, source-fragment, prompt, path, URI, encoding, linkage, poisoning, and cross-tenant attacks.",
        ["RELEASE-CONTRACT-140"],
        "curator",
        ["explorer", "architect", "integrator", "optimizer"],
        89,
        True,
        ["fixture:knowledge-adversarial"],
        [
            "src/hive_mind_os/knowledge/schemas/shared-learning-candidate-v1.schema.json",
            "docs/execution/LEARNING_POISONING_RESULTS.md",
            ".gitleaks.toml",
        ],
        [
            "tests/fixtures/knowledge/disclosure-cases.json",
            "tests/fixtures/knowledge/poisoning-cases.json",
            "tests/knowledge/test_adversarial_fixture_contract.py",
            "docs/execution/knowledge/ADVERSARIAL_CORPUS.md",
        ],
        ["python -m unittest tests.knowledge.test_adversarial_fixture_contract -v"],
        [
            "Fixtures are synthetic canaries and cannot be mistaken for live credentials, customer data, or copied proprietary material.",
            "Cases cover direct, encoded, split-field, filename, count/timing, graph-topology, neighbor, pseudonym-linkage, and prompt-injection disclosure paths.",
            "Every fixture has an expected deny, quarantine, or safe-release result and a recorded threat rationale.",
            "The corpus is independently reviewed for license cleanliness and absence of real secrets before integration.",
        ],
        "Release safety must be tested adversarially with retained negative evidence, not inferred from happy-path redaction examples.",
    ),
    node(
        "OBSIDIAN-SOURCE-160",
        "Admit current Obsidian compatibility sources",
        "Retain and adjudicate current official evidence for every Obsidian, Bases, Canvas, vault-refresh, and core-feature compatibility claim before naming those surfaces in product acceptance evidence.",
        ["SOURCE-010", "SCAFFOLD-040"],
        "explorer",
        ["curator", "integrator", "architect"],
        88,
        True,
        ["evidence:obsidian-source-admission"],
        [
            "docs/NEXT_SESSION_HANDOFF_OBSIDIAN_AGENT_REDESIGN.md",
            "docs/plan/knowledge-projection-tournament-2026-08-13/SOURCE_REGISTER.md",
            "AGENTS.md",
        ],
        [
            "evidence/sources/obsidian-compatibility/manifest.json",
            "evidence/sources/obsidian-compatibility/claims.json",
            "evidence/courts/CASE-OBSIDIAN-COMPATIBILITY-SOURCES.json",
            "tests/knowledge/test_obsidian_source_admission.py",
            "docs/execution/knowledge/OBSIDIAN_SOURCE_ADMISSION.md",
        ],
        ["python -m unittest tests.knowledge.test_obsidian_source_admission -v"],
        [
            "Every product claim about Obsidian core Markdown, Properties, Graph, Bases, Canvas, vault refresh, path behavior, or optional features has an official URI, retrieval time, product/version scope, retained digest, license/reuse disposition, atomic claim, and counterclaim.",
            "Unavailable, mutable, unlicensed, or ambiguous source material remains a blocking evidence obligation and narrows downstream claims to generic Markdown/YAML/JSON compatibility.",
            "The court separates compatibility evidence from any claim that Obsidian is an execution host, authority, required dependency, Sync service, or supported plugin surface.",
            "No external code or proprietary Obsidian asset is copied into the repository.",
        ],
        "The existing handoff cites official behavior but does not retain sufficiently pinned evidence for a new product compatibility claim.",
        required_inputs=[
            "evidence/knowledge-projection/source-inventory.json",
            "evidence/knowledge-projection/source-obligations.json",
        ],
    ),
    node(
        "RETENTION-170",
        "Resolve retention, deletion, and takedown",
        "Define append-only metadata and deletion receipts separately from protected or erasable bodies so credentials, customer data, and legally removable content are not made permanently irrecoverable to delete.",
        ["CLASSIFY-050", "IDENTITY-100"],
        "architect",
        ["curator", "steward", "integrator"],
        87,
        True,
        ["policy:knowledge-retention", "schema:payload-takedown"],
        [
            "src/hive_mind_os/brain_kernel/memory.py",
            "src/hive_mind_os/brain_kernel/store.py",
            "src/hive_mind_os/knowledge/classification.py",
            "src/hive_mind_os/knowledge/records.py",
            "docs/architecture/HUMAN_AUTHORITY_GATES.md",
        ],
        [
            "src/hive_mind_os/knowledge/retention.py",
            "src/hive_mind_os/knowledge/schemas/deletion-receipt-v1.schema.json",
            "src/hive_mind_os/knowledge/schemas/payload-reference-v1.schema.json",
            "tests/knowledge/test_retention.py",
            "docs/execution/knowledge/RETENTION_AND_TAKEDOWN.md",
        ],
        ["python -m unittest tests.knowledge.test_retention -v"],
        [
            "Immutable provenance metadata and non-reversible digests are separated from protected payload storage with explicit access, encryption/key-lifecycle, backup, retention, and deletion policy obligations.",
            "Authorized deletion, crypto-erasure where adopted, legal takedown, credential exposure, backup expiry, and restoration each emit a retained receipt without preserving the removed body in projections, logs, Git, fixtures, or error text.",
            "Unknown legal, ownership, customer, credential, or retention status quarantines the body and blocks shared release.",
            "A privacy/security and licensing expert obligation is resolved or explicitly blocks STORE-200; an agent label alone is not authenticated legal approval.",
        ],
        "Append-only provenance must preserve that a deletion occurred and why without forcing permanent retention of the sensitive body itself.",
    ),
    node(
        "STORE-200",
        "Implement the canonical private knowledge store",
        "Implement append-only durable knowledge events, typed reducers, referential integrity, idempotency, snapshots, and one declared ownership boundary over canonical graph records.",
        ["AUTHORITY-020", "COVERAGE-120", "IDENTITY-100", "RETENTION-170"],
        "builder",
        ["architect", "steward", "curator"],
        88,
        False,
        ["durability:knowledge-event-store", "iface:canonical-knowledge-store"],
        [
            "src/hive_mind_os/brain_kernel/events.py",
            "src/hive_mind_os/brain_kernel/store.py",
            "src/hive_mind_os/brain_kernel/memory.py",
            "src/hive_mind_os/ledger.py",
            "src/hive_mind_os/prompt_registry.py",
            "src/hive_mind_os/knowledge/records.py",
            "src/hive_mind_os/knowledge/coverage.py",
        ],
        [
            "src/hive_mind_os/knowledge/store.py",
            "src/hive_mind_os/knowledge/reducer.py",
            "tests/knowledge/test_store.py",
            "tests/knowledge/test_reducer.py",
            "docs/execution/knowledge/CANONICAL_STORE.md",
        ],
        [
            "python -m unittest tests.knowledge.test_store -v",
            "python -m unittest tests.knowledge.test_reducer -v",
        ],
        [
            "The architecture names one canonical owner or an explicit immutable reference adapter for every record type; unresolved dual authority fails closed.",
            "Events are content-bound, ordered, tenant/repository scoped, idempotent, and reject missing or cross-boundary references.",
            "Mutable views and snapshots rebuild from verified events and cannot become authority.",
            "Concurrent append, torn write, stale expected head, duplicate identity, corrupt chain, and point-in-time cutoff tests pass.",
            "Protected canonical state is outside any shared/public repository by default and records backup/retention obligations honestly.",
        ],
        "A truthful complete graph needs one durable event boundary rather than a projector joining contradictory mutable views.",
        required_inputs=[
            "evidence/knowledge-projection/source-inventory.json",
            "evidence/knowledge-projection/source-obligations.json",
        ],
    ),
    node(
        "IDEA-RUNTIME-210",
        "Implement repeated idea-pass behavior",
        "Implement transactional idea encounter, deduplication, immutable pass creation, remand, appeal, reversal, re-entry, and successor-work operations.",
        ["IDEA-110", "LEARNING-030", "STORE-200"],
        "builder",
        ["explorer", "optimizer", "orchestrator", "curator"],
        87,
        True,
        ["iface:idea-runtime"],
        [
            "src/hive_mind_os/knowledge/ideas.py",
            "src/hive_mind_os/knowledge/store.py",
            "src/hive_mind_os/brain_kernel/planner.py",
            "src/hive_mind_os/brain_kernel/reconciler.py",
        ],
        [
            "src/hive_mind_os/knowledge/idea_runtime.py",
            "tests/knowledge/test_idea_runtime.py",
            "docs/execution/knowledge/IDEA_RUNTIME.md",
        ],
        ["python -m unittest tests.knowledge.test_idea_runtime -v"],
        [
            "Every Explorer candidate emits an encounter before filtering, including duplicates, abandoned, invalid, trivial, blocked, and quarantined candidates.",
            "Atomic compare/register/relate prevents concurrent duplicate canonical ideas and retains collision receipts.",
            "One fixture idea completes at least three passes caused by different triggers while every prior pass and disposition remains addressable.",
            "No operation rewrites an earlier pass, changes a record type in place, or introduces a cycle into the execution dependency graph.",
        ],
        "The user's repeated-loop requirement is satisfied by append-only successor passes, not mutable status rewinds.",
    ),
    node(
        "GRAPH-ADAPTERS-220",
        "Connect roles, courts, work, delivery, and learning",
        "Adapt all specialist and temporary court outputs into typed canonical records and edges without treating adapter output as independent evidence.",
        ["COVERAGE-120", "LEARNING-030", "STORE-200"],
        "builder",
        ["orchestrator", "explorer", "architect", "curator", "integrator", "steward", "optimizer"],
        86,
        True,
        ["iface:knowledge-adapters"],
        [
            "src/hive_mind_os/brain_kernel/roles.py",
            "src/hive_mind_os/brain_kernel/court_runtime.py",
            "src/hive_mind_os/brain_kernel/challengers.py",
            "src/hive_mind_os/brain_kernel/evaluation_runtime.py",
            "src/hive_mind_os/brain_kernel/promotion.py",
            "src/hive_mind_os/knowledge/store.py",
        ],
        [
            "src/hive_mind_os/knowledge/adapters.py",
            "src/hive_mind_os/knowledge/graph.py",
            "tests/knowledge/test_adapters.py",
            "tests/knowledge/test_graph.py",
            "docs/execution/knowledge/GRAPH_ADAPTERS.md",
        ],
        [
            "python -m unittest tests.knowledge.test_adapters -v",
            "python -m unittest tests.knowledge.test_graph -v",
        ],
        [
            "All eight roles, court briefs/testimony/verdicts/dissent/appeals, work attempts, verification, integration, delivery, incidents, authority, outcomes, lessons, champions, challengers, evaluations, promotions, and rollbacks have typed adapters.",
            "Every adapter preserves source IDs/digests and maturity evidence and rejects missing, ambiguous, or conflicting authority.",
            "The Clerk is represented without granting judgment authority; judges remain independent from scout, advocate, architect, builder, and affected champion identities.",
            "An end-to-end graph query can distinguish idea, work, candidate, deliverable, outcome, and lesson rather than mutating one object's type.",
        ],
        "The graph must expose what each role actually did and why gates returned work, while preserving independence and implementation maturity.",
    ),
    node(
        "PRIVATE-PROJECTOR-230",
        "Build the one-shot private knowledge projector",
        "Build a deterministic, interruption-safe, read-only Markdown/YAML projector from the verified canonical store into an external per-repository private vault.",
        ["CLASSIFY-050", "PROJECT-CONTRACT-130", "STORE-200"],
        "builder",
        ["integrator", "steward", "curator"],
        85,
        True,
        ["iface:private-knowledge-projector"],
        [
            "src/hive_mind_os/knowledge/projection_contracts.py",
            "src/hive_mind_os/knowledge/store.py",
            "src/hive_mind_os/projection.py",
        ],
        [
            "src/hive_mind_os/knowledge/projector.py",
            "tests/knowledge/test_projector.py",
            "docs/execution/knowledge/PRIVATE_PROJECTOR.md",
        ],
        ["python -m unittest tests.knowledge.test_projector -v"],
        [
            "Identical source head and renderer version produce byte-identical files, manifest, cursor, and receipt.",
            "Staged publication yields either the old complete projection or the new complete projection; source drift or human edits leave retained conflicts and no silent overwrite.",
            "The projection includes full logical coverage but excludes raw secrets, credentials, hidden reasoning, raw transcripts, and unbounded tool/model bodies even from the private vault.",
            "Deleting the generated view and rebuilding it does not mutate canonical state; operation works with Obsidian absent.",
            "The projector has no shared-release authority and excludes its own generated files from novelty intake.",
        ],
        "The smallest credible MVP is a one-shot external private projection; watcher, Inbox, and shared publication add unnecessary initial authority and risk.",
    ),
    node(
        "RELEASE-CANDIDATE-240",
        "Build allowlisted learning candidates",
        "Derive minimal inert shared-learning candidates from private records without copying private payloads, identities, filenames, counts, timing, or graph topology.",
        ["CLASSIFY-050", "RELEASE-CONTRACT-140", "STORE-200"],
        "builder",
        ["integrator", "curator", "optimizer"],
        84,
        True,
        ["iface:shared-learning-candidate"],
        [
            "src/hive_mind_os/knowledge/classification.py",
            "src/hive_mind_os/knowledge/release_contracts.py",
            "src/hive_mind_os/knowledge/store.py",
            ".autopilot/bin/learning.py",
        ],
        [
            "src/hive_mind_os/knowledge/release_candidate.py",
            "tests/knowledge/test_release_candidate.py",
            "docs/execution/knowledge/RELEASE_CANDIDATES.md",
        ],
        ["python -m unittest tests.knowledge.test_release_candidate -v"],
        [
            "Candidate construction reads only explicitly mapped private fields and produces only fields allowed by the shared schema.",
            "Each abstraction states mechanism, applicability, constraints, counterexamples, measured outcome status, uncertainty, expiry, and non-reversible evidence digests.",
            "Unknown classification, unresolved provenance/license, private linkage, or insufficient abstraction yields a retained denial rather than partial output.",
            "Candidate bytes remain outside Git/shared state until RELEASE-GATE-320 issues an independent decision.",
            "Before RELEASE-COURT-510, all retained candidate-builder and registry qualification inputs are synthetic, license-clean fixtures; no real private repository record is admitted to learning state.",
        ],
        "A private record is not a public record with some strings removed; shared candidates must be newly composed from an allowlist.",
    ),
    node(
        "OBSIDIAN-VIEWS-300",
        "Render the private Obsidian-compatible graph",
        "Render stable linked notes plus HOME, Bases-compatible tables, Canvas-compatible timelines, legends, gate/role/type/status distinctions, and every permitted relationship edge.",
        ["GRAPH-ADAPTERS-220", "IDEA-RUNTIME-210", "OBSIDIAN-SOURCE-160", "PRIVATE-PROJECTOR-230"],
        "integrator",
        ["builder", "explorer", "steward", "curator"],
        83,
        True,
        ["iface:obsidian-compatible-view"],
        [
            "src/hive_mind_os/knowledge/graph.py",
            "src/hive_mind_os/knowledge/idea_runtime.py",
            "src/hive_mind_os/knowledge/projector.py",
            "docs/NEXT_SESSION_HANDOFF_OBSIDIAN_AGENT_REDESIGN.md",
        ],
        [
            "src/hive_mind_os/knowledge/obsidian.py",
            "tests/knowledge/test_obsidian_views.py",
            "docs/execution/knowledge/OBSIDIAN_VIEWS.md",
        ],
        ["python -m unittest tests.knowledge.test_obsidian_views -v"],
        [
            "Notes exist for all permitted record families and stable links expose sources, claims, ideas/passes, courts, roles, work, candidates, tests, delivery, outcomes, lessons, champions, and challengers.",
            "The visual vocabulary pairs color with shape/text for record type, gate, role, immutable fact, status, private/shared boundary, and maturity; missing edges become coverage failures.",
            "Backward semantic edges identify their reason and successor pass while the execution DAG remains visibly acyclic.",
            "Core Markdown/YAML/JSON consumers can use every essential record without Obsidian-specific syntax; optional Bases/Canvas files remain rebuildable views.",
        ],
        "Obsidian is the preferred human graph interface, not the store, scheduler, execution host, or sole way to read the records.",
    ),
    node(
        "TRACE-310",
        "Explain end-to-end history and every return",
        "Implement point-in-time trace and time-expanded path reconstruction from source through outcomes and across every remand, reversal, rollback, and later pass.",
        ["GRAPH-ADAPTERS-220", "IDEA-RUNTIME-210", "STORE-200"],
        "steward",
        ["orchestrator", "explorer", "optimizer", "curator"],
        82,
        True,
        ["iface:knowledge-trace"],
        [
            "src/hive_mind_os/knowledge/graph.py",
            "src/hive_mind_os/knowledge/idea_runtime.py",
            "src/hive_mind_os/knowledge/store.py",
            "src/hive_mind_os/brain_kernel/reconciler.py",
        ],
        [
            "src/hive_mind_os/knowledge/trace.py",
            "tests/knowledge/test_trace.py",
            "docs/execution/knowledge/TRACE_AND_TIME_TRAVEL.md",
        ],
        ["python -m unittest tests.knowledge.test_trace -v"],
        [
            "Queries explain what the system knew at a commit/time and cannot see later events or decisions.",
            "Every backward transition reports exact trigger, evidence, originating gate/role, destination, prior and successor IDs, and effect on work/deliverable status.",
            "A source-to-outcome-to-lesson-to-reentry trace is complete, deterministic, and digest-bound.",
            "Orphans, missing mandatory edges, last-write-wins duplicate decisions, and inconsistent authorities fail closed.",
        ],
        "A graph is useful for learning only if it preserves why the system considered alternatives and why work moved backward.",
    ),
    node(
        "RELEASE-GATE-320",
        "Implement the offline shared-release gateway",
        "Implement default-deny structural, sensitivity, license, provenance, de-identification, disclosure, poisoning, independence, and revocation gates for offline release bundles.",
        ["ADVERSARY-150", "AUTHORITY-020", "LEARNING-030", "RELEASE-CANDIDATE-240"],
        "builder",
        ["curator", "architect", "integrator", "optimizer"],
        81,
        False,
        ["gate:offline-shared-release"],
        [
            "src/hive_mind_os/knowledge/release_candidate.py",
            "src/hive_mind_os/knowledge/classification.py",
            "tests/fixtures/knowledge/",
            "src/hive_mind_os/brain_kernel/court_runtime.py",
        ],
        [
            "src/hive_mind_os/knowledge/release_gateway.py",
            "tests/knowledge/test_release_gateway.py",
            "tests/knowledge/test_release_leakage.py",
            "docs/execution/knowledge/RELEASE_GATE.md",
        ],
        [
            "python -m unittest tests.knowledge.test_release_gateway -v",
            "python -m unittest tests.knowledge.test_release_leakage -v",
        ],
        [
            "Every release requires separate builder, reproducing Curator, and distinct Judge identities plus resolved expert obligations appropriate to privacy and license risk.",
            "All adversarial fixtures are denied or quarantined as expected; known secret, private, proprietary, cross-tenant, and source-fragment leakage count is zero.",
            "Unknown schema, classifier, policy, evidence, license, provenance, identity, expiry, or authority denies release and records the reason.",
            "The gateway emits an immutable offline bundle and decision receipt only; it has no remote transport capability.",
            "Revocation creates a signed tombstone and exposure record without erasing private history.",
            "All pre-release qualification and local-registry admissions use synthetic, license-clean fixtures; real private records remain in protected canonical state until a later exact release court authorizes their class and use.",
        ],
        "Automatic public export and model-only redaction remain quarantined; the first gateway is deterministic, offline, independently judged, and separately authorized.",
    ),
    node(
        "SHARED-REGISTRY-330",
        "Implement the local sanitized registry",
        "Implement a content-addressed local registry for approved safe abstractions, revocations, counterexamples, and read-only lookup with no remote write adapter.",
        ["RELEASE-GATE-320"],
        "integrator",
        ["steward", "curator", "optimizer"],
        80,
        False,
        ["store:local-shared-learning-registry"],
        [
            "src/hive_mind_os/knowledge/release_gateway.py",
            "src/hive_mind_os/knowledge/release_contracts.py",
            ".autopilot/lessons/README.md",
        ],
        [
            "src/hive_mind_os/knowledge/shared_registry.py",
            "tests/knowledge/test_shared_registry.py",
            "docs/execution/knowledge/LOCAL_SHARED_REGISTRY.md",
        ],
        ["python -m unittest tests.knowledge.test_shared_registry -v"],
        [
            "Only exact gateway-approved bundles enter the registry; altered, revoked, stale, duplicate/sybil, cross-tenant, or unsigned records fail closed.",
            "Consumers receive inert structured data, counterexamples, expiry, applicability, and decision receipts but no private source body or reversible identifier.",
            "Registry corruption, stale head, concurrent insert, tombstone, export/import, and deterministic rebuild tests pass.",
            "No code path writes to a remote repository, service, or public vault; such transport remains deferred to a separately authorized future DAG.",
            "Before RELEASE-COURT-510, every admitted registry record derives only from the synthetic, license-clean fixture corpus and is visibly marked non-production qualification evidence.",
        ],
        "A qualified local registry proves contracts and consumption boundaries before any difficult-to-reverse cross-repository publication is considered.",
    ),
    node(
        "CLI-340",
        "Expose bounded knowledge commands",
        "Expose init, project, query, trace, doctor, candidate, offline-release-check, and local-registry commands with typed output, dry-run boundaries, and no implicit watcher or remote effect.",
        ["OBSIDIAN-VIEWS-300", "SHARED-REGISTRY-330", "TRACE-310"],
        "builder",
        ["integrator", "steward", "curator"],
        79,
        False,
        ["iface:knowledge-cli"],
        [
            "src/hive_mind_os/cli.py",
            "src/hive_mind_os/knowledge/obsidian.py",
            "src/hive_mind_os/knowledge/trace.py",
            "src/hive_mind_os/knowledge/shared_registry.py",
        ],
        [
            "src/hive_mind_os/knowledge/cli.py",
            "src/hive_mind_os/cli.py",
            "tests/knowledge/test_cli.py",
            "docs/execution/knowledge/CLI.md",
        ],
        ["python -m unittest tests.knowledge.test_cli -v"],
        [
            "All commands use explicit repository/tenant/state/vault boundaries, safe path handling, typed JSON output, and capability checks.",
            "Projection is one-shot by default; Inbox, watch mode, and remote registry commands are absent.",
            "Dry-run release checks cannot materialize a bundle or mutate either private or registry state.",
            "Errors redact secrets and private content and distinguish missing evidence from completed work.",
        ],
        "A narrow CLI makes the private MVP testable without prematurely granting persistent watchers, bidirectional intake, or remote publication authority.",
    ),
    node(
        "PRIOR-ART-400",
        "Use shared learning as read-only prior art",
        "Add bounded read-only prior-art and duplicate-candidate lookup for Explorer and Optimizer while preserving local judgment and zero authority expansion.",
        ["IDEA-RUNTIME-210", "SHARED-REGISTRY-330"],
        "optimizer",
        ["explorer", "curator", "architect"],
        78,
        True,
        ["iface:shared-prior-art"],
        [
            "src/hive_mind_os/brain_kernel/explorer.py",
            "src/hive_mind_os/brain_kernel/optimizer.py",
            "src/hive_mind_os/knowledge/idea_runtime.py",
            "src/hive_mind_os/knowledge/shared_registry.py",
        ],
        [
            "src/hive_mind_os/knowledge/prior_art.py",
            "src/hive_mind_os/brain_kernel/explorer.py",
            "src/hive_mind_os/brain_kernel/optimizer.py",
            "tests/knowledge/test_prior_art.py",
            "docs/execution/knowledge/PRIOR_ART.md",
        ],
        ["python -m unittest tests.knowledge.test_prior_art -v"],
        [
            "Lookup records exact registry IDs, versions, cutoff, query, candidates, ranking rationale, exclusions, and context digest presented to the role.",
            "A match may classify a duplicate, refinement, contradiction, or local experiment candidate but cannot install code, execute Markdown, grant authority, or promote a challenger.",
            "Revoked, expired, quarantined, mismatched-applicability, and poisoned records are excluded.",
            "Controlled evaluation measures duplicate escape, false merge, repeated-idea rate, and outcome effects; improvement remains a hypothesis until evidence exists.",
        ],
        "The shared registry avoids repeated ideas only if it is auditable prior art rather than an untrusted instruction feed.",
    ),
    node(
        "FEDERATION-410",
        "Qualify multi-repository isolation and self-host guards",
        "Implement local read-only federation across released abstractions with tenant isolation, release-scoped pseudonyms, source-tree validation, and recursion guards for self-host operation.",
        ["CLASSIFY-050", "OBSIDIAN-VIEWS-300", "SHARED-REGISTRY-330"],
        "integrator",
        ["steward", "curator", "explorer"],
        77,
        True,
        ["iface:knowledge-federation"],
        [
            "src/hive_mind_os/knowledge/obsidian.py",
            "src/hive_mind_os/knowledge/shared_registry.py",
            "docs/plan/knowledge-projection-tournament-2026-08-13/SOURCE_REGISTER.md",
        ],
        [
            "src/hive_mind_os/knowledge/federation.py",
            "src/hive_mind_os/knowledge/self_host.py",
            "tests/knowledge/test_federation.py",
            "tests/knowledge/test_self_host.py",
            "docs/execution/knowledge/FEDERATION.md",
        ],
        [
            "python -m unittest tests.knowledge.test_federation -v",
            "python -m unittest tests.knowledge.test_self_host -v",
        ],
        [
            "Private repository or tenant records cannot be selected, inferred, linked, counted, or projected by another scope.",
            "Portfolio views materialize only locally approved shared records and never nest vaults or treat cross-vault paths as identity.",
            "Generated notes, projection events, registry reads, and telemetry do not re-enter novelty discovery as new evidence or ideas.",
            "Hop, depth, origin, observation-epoch, controller, and subject guards stop self-analysis and delegation feedback loops.",
        ],
        "Prior prototype patterns are useful evidence, but current-baseline contracts and adversarial isolation tests must independently requalify them.",
    ),
    node(
        "MIGRATION-420",
        "Provide migration, backup, restore, and rollback",
        "Implement versioned import adapters, shadow backfill, coverage comparison, backup/restore, downgrade, and projector/registry rollback without relabeling old stores as canonical.",
        ["PRIVATE-PROJECTOR-230", "SHARED-REGISTRY-330", "STORE-200"],
        "steward",
        ["integrator", "architect", "curator"],
        76,
        True,
        ["iface:knowledge-migration"],
        [
            "src/hive_mind_os/brain_kernel/store.py",
            "src/hive_mind_os/brain_kernel/memory.py",
            "src/hive_mind_os/ledger.py",
            "src/hive_mind_os/knowledge/store.py",
            "src/hive_mind_os/knowledge/projector.py",
            "src/hive_mind_os/knowledge/shared_registry.py",
        ],
        [
            "src/hive_mind_os/knowledge/migration.py",
            "src/hive_mind_os/knowledge/backup.py",
            "tests/knowledge/test_migration.py",
            "tests/knowledge/test_backup.py",
            "docs/execution/knowledge/MIGRATION_AND_ROLLBACK.md",
        ],
        [
            "python -m unittest tests.knowledge.test_migration -v",
            "python -m unittest tests.knowledge.test_backup -v",
        ],
        [
            "Backfill is read-only against legacy stores, idempotent, point-in-time bound, and reports unmapped, duplicate, conflicting, or unverifiable records.",
            "Shadow projections compare coverage and digests before any adapter becomes the default.",
            "Backup/restore verifies canonical event integrity, projection rebuild, registry tombstones, classifications, and tenant isolation.",
            "Rollback disables a version and rebuilds views from retained canonical history; it never deletes dissent, losing ideas, or adverse evidence.",
        ],
        "The repository contains several stores and an unmerged prototype, so migration must be explicit and reversible rather than an implicit merge or copy.",
        required_inputs=[
            "evidence/knowledge-projection/source-inventory.json",
            "evidence/knowledge-projection/source-obligations.json",
        ],
    ),
    node(
        "DASHBOARDS-430",
        "Complete human and machine knowledge views",
        "Build generated coverage, role maturity, idea family, court, loop, champion/challenger, delivery, outcome, release, conflict, stale-record, and knowledge-health dashboards.",
        ["OBSIDIAN-VIEWS-300", "PRIOR-ART-400", "TRACE-310"],
        "integrator",
        ["orchestrator", "explorer", "steward", "optimizer", "curator"],
        75,
        True,
        ["iface:knowledge-dashboards"],
        [
            "src/hive_mind_os/knowledge/obsidian.py",
            "src/hive_mind_os/knowledge/prior_art.py",
            "src/hive_mind_os/knowledge/trace.py",
            "src/hive_mind_os/knowledge/coverage.py",
        ],
        [
            "src/hive_mind_os/knowledge/dashboards.py",
            "tests/knowledge/test_dashboards.py",
            "docs/execution/knowledge/DASHBOARDS.md",
        ],
        ["python -m unittest tests.knowledge.test_dashboards -v"],
        [
            "Views answer what is done, in progress, pending, blocked, not started, implemented in code, documentation-only, prototype-only, and independently verified.",
            "Idea-family views expose every pass, gate, advocate/cross-examiner/expert/judge, return reason, work/deliverable type change, champion/challenger comparison, and outcome.",
            "Coverage views expose missing record types, missing edges, orphans, contradictions, stale facts, unresolved evidence obligations, and unowned records.",
            "Private versus approved-shared records and every Obsidian write path are visibly distinguished without leaking excluded records through counts or topology.",
        ],
        "A demo-grade graph must make status and evidence maturity legible to beginners without overstating code completion to experts.",
    ),
    node(
        "QUALIFY-500",
        "Run end-to-end local qualification",
        "Independently qualify a multi-repository local mission from idea encounter through repeated passes, delivery outcome, private projection, offline release, local prior-art lookup, restoration, and rollback.",
        ["ADVERSARY-150", "CLI-340", "DASHBOARDS-430", "FEDERATION-410", "MIGRATION-420", "PRIOR-ART-400"],
        "curator",
        ["orchestrator", "explorer", "architect", "builder", "integrator", "steward", "optimizer"],
        74,
        False,
        ["gate:knowledge-qualification"],
        [
            "src/hive_mind_os/knowledge/",
            "tests/fixtures/knowledge/",
            "docs/execution/knowledge/",
            "docs/architecture/HARDENED_VISION_CONTRACT.md",
        ],
        [
            "tests/knowledge/test_end_to_end.py",
            "tests/knowledge/test_no_obsidian_dependency.py",
            "evidence/qualification/knowledge-projection/summary.json",
            "evidence/qualification/knowledge-projection/receipts.json",
            "docs/execution/knowledge/QUALIFICATION_RESULTS.md",
        ],
        [
            "python -m unittest tests.knowledge.test_end_to_end -v",
            "python -m unittest tests.knowledge.test_no_obsidian_dependency -v",
        ],
        [
            "An exact candidate demonstrates all eight roles, independent court seats, three idea passes, two different backward triggers, typed transformations, delivery/outcome, champion/challenger evaluation, and later lesson retrieval.",
            "Deterministic rebuild, interrupted render, concurrent writer, stale cursor, human edit, rename, corruption, point-in-time cutoff, cross-tenant canary, revocation, restoration, and rollback tests pass on Windows and one independent platform obligation is recorded.",
            "Known private, secret, customer, proprietary, source, prompt, URI/path, and license-incompatible leakage count is zero and every adversarial gate-bypass attempt fails.",
            "The full repository CI is run once by the integration transaction and no baseline requirement or test is weakened.",
            "Remote release, watcher, Inbox intake, and automatic shared-lesson-to-challenger behavior remain absent and quarantined.",
            "The multi-repository release and registry scenario uses only synthetic, license-clean fixtures; it does not publish or admit a real private repository record.",
        ],
        "Only exact-candidate, independent, end-to-end evidence can move the architecture from planned components to a qualified local product claim.",
    ),
    node(
        "RELEASE-COURT-510",
        "Judge local release and residual obligations",
        "Convene an exact-candidate court with separate Advocate, Cross-Examiner, privacy/security and licensing experts, Curator evidence, Judge, dissent, and appeal path.",
        ["QUALIFY-500"],
        "curator",
        ["orchestrator", "architect", "integrator", "steward", "optimizer"],
        73,
        False,
        ["court:knowledge-local-release"],
        [
            "evidence/qualification/knowledge-projection/summary.json",
            "evidence/qualification/knowledge-projection/receipts.json",
            "docs/plan/knowledge-projection-tournament-2026-08-13/TOURNAMENT_RESULTS.json",
            "docs/architecture/HUMAN_AUTHORITY_GATES.md",
            "docs/plan/BLOCKERS.md",
        ],
        [
            "evidence/courts/CASE-KNOWLEDGE-PROJECTION-LOCAL-RELEASE.json",
            "tests/knowledge/test_release_court.py",
            "docs/execution/knowledge/LOCAL_RELEASE_DECISION.md",
        ],
        ["python -m unittest tests.knowledge.test_release_court -v"],
        [
            "Judge identity differs from scout, advocate, architect, builder, Curator, and affected champion; every brief and expert obligation is retained.",
            "The decision establishes procedural role separation only and does not claim authenticated independent-human identity.",
            "The verdict is one of adopt, adapt, defer, reject, or quarantine and maps each accepted claim to tests, metrics, rollback, ownership, and open obligations.",
            "The court cannot authorize external shared publication without closing authenticated identity and durable external retention blockers, transport-specific threat evidence, and a new authority grant.",
            "Dissent, negative results, deferred Obsidian evidence, deletion/takedown policy, and any appeal remain append-only.",
        ],
        "Passing tests is evidence, not self-judgment; architecture, privacy, licensing, and authority claims require a distinct decision identity.",
    ),
    node(
        "HANDOFF-520",
        "Deliver the bounded product handoff",
        "Document setup, no-Obsidian operation, graph legend, roles, gates, record types, repeated-pass workflow, privacy boundary, status evidence, rollback, and the next separately governed program.",
        ["RELEASE-COURT-510"],
        "orchestrator",
        ["explorer", "architect", "builder", "curator", "integrator", "steward", "optimizer"],
        72,
        False,
        ["handoff:knowledge-product"],
        [
            "docs/execution/knowledge/",
            "evidence/courts/CASE-KNOWLEDGE-PROJECTION-LOCAL-RELEASE.json",
            "USER_GUIDE/00_START_HERE.md",
            "README.md",
        ],
        [
            "USER_GUIDE/09_KNOWLEDGE_GRAPH.md",
            "docs/execution/knowledge/DEMO_WORKFLOW.md",
            "docs/execution/knowledge/STATUS_MATRIX.md",
            "docs/execution/knowledge/NEXT_PROGRAM.md",
            "tests/knowledge/test_handoff.py",
        ],
        [
            "python docs/execution/dags/knowledge-projection-v1/verify_plan.py",
            "python -m unittest tests.knowledge.test_handoff -v",
        ],
        [
            "A beginner can create and read a private projection without Obsidian; an expert can verify every record, edge, cursor, gate, decision, and receipt.",
            "The handoff distinguishes implemented, qualified, deferred, rejected, and quarantined capabilities and never equates documents, PRs, role presence, or prior DAG completion with code completion.",
            "Automatic remote/public release, bidirectional Obsidian intake, persistent watch mode, and automatic shared learning activation are listed only as separately governed future work.",
            "The final full CI and plan verification pass without editing .autopilot/plan.json or weakening any baseline control.",
        ],
        "The first release should be a safe local knowledge product with honest boundaries, not an implicit authorization for difficult-to-reverse public effects.",
    ),
]
