"""Immutable Appeals-Judge-authorized contracts for the FPC appeal."""
from __future__ import annotations

BASELINE_COMMIT = "20e26e3c53d41ec4093b23f0957766cd0cbdab70"
BASELINE_TREE = "f454db6d64120c946ae6700bcf4b4b6ea1bef26c"
CAUSALITY_RECEIPT = "sha256:4de1070a524f50ffbc966dbfcbede37df9b97af44ffc49d660e9f3195bcb7313"
DISCOVERY_COUNT = 1059
DISCOVERY_DIGEST = "sha256:8c6047bd0457cd3b880437c466695527e6a8bc342724bab008aac5cebf0d477c"
FROZEN_AUTOPILOT_PLAN = "sha256:85fd0c69fed4aa8cd40019bfeaccc5a686fa408ae5183060ae0320d412cea9ef"
ROOT_CI = "<venv>/Scripts/python.exe -E -s -m unittest discover -s tests -v"
RUNNER_TIMEOUT_SECONDS = 2700
DAG_DIR = "docs/execution/dags/fixture-prerequisite-causality-appeal-v1"
OPENING = "evidence/courts/CASE-FIXTURE-PREREQUISITE-CAUSALITY-APPEAL-OPENING.json"
EVIDENCE = "evidence/performance/fixture-prerequisite-causality-appeal-v1"

COMMON_INPUTS = [
    "AGENTS.md", "docs/execution/DAG_AUTHORING_STANDARD.md",
    "evidence/performance/fixture-prerequisite-v1/causality.json",
    "docs/execution/dags/fixture-prerequisite-v1/manifest.json",
    "tests/test_autopilot_fixture_seed.py", ".autopilot/tests/test_healing.py",
]
SEAL_OUTPUTS = [
    f"{DAG_DIR}/README.md", f"{DAG_DIR}/.gitignore", f"{DAG_DIR}/specs.py",
    f"{DAG_DIR}/generate_plan.py", f"{DAG_DIR}/verify_plan.py", f"{DAG_DIR}/runner.py",
    f"{DAG_DIR}/manifest.json", OPENING,
]

SPECS = [
 {"id":"FPC-SEAL-000","title":"Seal fixture prerequisite causality appeal","objective":"As Clerk and Architect, seal this separate no-code causality appeal before any new claim, execution, or judgment.","rationale":"The predecessor receipt is incomplete and records 1,059 discovered tests, not the sealed 1,050 inventory.","dependencies":[],"primary_role":"orchestrator","court_seat":"clerk-and-architect","consulted_roles":["curator","steward","integrator"],"required_inputs":COMMON_INPUTS,"expected_outputs":SEAL_OUTPUTS,"read_scope":COMMON_INPUTS,"write_scope":SEAL_OUTPUTS,"required_tests":[f"python {DAG_DIR}/verify_plan.py",f"python {DAG_DIR}/runner.py self-test"],"acceptance_criteria":["Exactly six Judge-required nodes compile in deterministic rounds.","The baseline commit/tree, causality receipt digest, 1,059 discovery count/digest, frozen plan digest, and 2,700-second serialized execution bound are pinned.","The seal grants no implementation, fixture promotion, GCO promotion, performance conclusion, or knowledge BASELINE retry authority."],"parallel_safe":False,"semantic_locks":["contract:fixture-prerequisite-causality-appeal-v1"],"critical_path_importance":100,"stopping_condition":"Commit only declared seal artifacts after self-test, verifier, strict lint, and rounds pass.","rollback":"Revert only this retained seal commit; predecessor evidence remains immutable."},
 {"id":"FPC-DISCOVERY-010","title":"Reconcile discovery identity and causal predicate","objective":"As independent Explorer and Advocate, explain the 1,059-ID discovery result and define the exact hermetic predicate without running implementation.","rationale":"The appeal must distinguish discovery, execution, skips, import origin, and timeout evidence before retrying root CI.","dependencies":["FPC-SEAL-000"],"primary_role":"explorer","court_seat":"independent-explorer-and-advocate","consulted_roles":["curator","steward"],"required_inputs":[f"{DAG_DIR}/runner.py","evidence/performance/fixture-prerequisite-v1/causality.json"],"expected_outputs":[f"{EVIDENCE}/discovery-analysis.json"],"read_scope":["tests/","pyproject.toml","src/hive_mind_os","evidence/performance/fixture-prerequisite-v1/causality.json"],"write_scope":[f"{EVIDENCE}/discovery-analysis.json"],"required_tests":[f"python {DAG_DIR}/runner.py verify --receipt {EVIDENCE}/discovery-analysis.json --phase discovery"],"acceptance_criteria":["Receipt binds exactly 1,059 discovered IDs and digest.","It states whether the predecessor 1,050/one-failure/eight-skip predicate is falsified, repairable, or needs split evidence.","No root-CI execution or code change occurs in this node."],"parallel_safe":True,"semantic_locks":["evidence:fpc-discovery"],"critical_path_importance":95,"stopping_condition":"Write one verifier-bound analysis or blocker receipt and stop.","rollback":"Revert only this evidence commit."},
 {"id":"FPC-EXECUTE-020","title":"Run one hermetic root-CI causality execution","objective":"As independent Curator, run exactly one serialized 2,700-second hermetic source-installed root-CI execution and retain a complete transcript receipt.","rationale":"Only a complete bounded execution can resolve the incomplete predecessor inventory.","dependencies":["FPC-SEAL-000","FPC-DISCOVERY-010"],"primary_role":"curator","court_seat":"independent-execution-curator","consulted_roles":["steward","optimizer"],"required_inputs":[f"{DAG_DIR}/runner.py",f"{EVIDENCE}/discovery-analysis.json"],"expected_outputs":[f"{EVIDENCE}/execution.json",f"{EVIDENCE}/execution-transcript.json"],"read_scope":["tests/","src/hive_mind_os","pyproject.toml",f"{EVIDENCE}/discovery-analysis.json"],"write_scope":[f"{EVIDENCE}/execution.json",f"{EVIDENCE}/execution-transcript.json"],"required_tests":[f"python {DAG_DIR}/runner.py verify --receipt {EVIDENCE}/execution.json --phase execution"],"acceptance_criteria":["Fresh editable-install venv, PYTHONNOUSERSITE=1, cleared PYTHONPATH, -E -s, source import origin, exact command, and one serialized 2,700-second budget are recorded.","Transcript retains complete command/result/failure/error/skip inventory or explicit timeout/truncation evidence.","No implementation, test mutation, persistent cache, network effect, or retry occurs."],"parallel_safe":True,"semantic_locks":["execution:fpc-root-ci"],"critical_path_importance":90,"stopping_condition":"One execution and durable transcript receipt are written; never rerun in this node; it may run alongside the independent Cross node only.","rollback":"Revert only this receipt commit; do not erase external transcript evidence."},
 {"id":"FPC-CROSS-030","title":"Cross-examine fixture causality appeal","objective":"As a separate Cross-Examiner, challenge provenance, environment, inventory, timeout, import, and causal conclusions without code changes.","rationale":"An adverse interpretation must be retained independently of execution evidence.","dependencies":["FPC-SEAL-000","FPC-DISCOVERY-010"],"primary_role":"curator","court_seat":"cross-examiner-distinct","consulted_roles":["advocate","steward"],"required_inputs":[f"{DAG_DIR}/runner.py",f"{EVIDENCE}/discovery-analysis.json"],"expected_outputs":[f"{EVIDENCE}/cross-examination.json"],"read_scope":["tests/","src/hive_mind_os","evidence/performance/fixture-prerequisite-v1/causality.json",f"{EVIDENCE}/discovery-analysis.json"],"write_scope":[f"{EVIDENCE}/cross-examination.json"],"required_tests":[f"python {DAG_DIR}/runner.py verify --receipt {EVIDENCE}/cross-examination.json --phase cross"],"acceptance_criteria":["Cross receipt preserves counterclaims for discovery mismatch, timeout, contamination, fixture non-causality, and unauthorized scope.","It does not modify code or rely on an unrecorded execution."],"parallel_safe":True,"semantic_locks":["evidence:fpc-cross"],"critical_path_importance":85,"stopping_condition":"Record independent adverse findings and stop.","rollback":"Revert only this receipt commit."},
 {"id":"FPC-INTEGRATE-040","title":"Integrate causal evidence","objective":"As Integrator, reconcile discovery, one execution, and cross-examination into a narrow causal disposition.","rationale":"The court needs explicit agreement or contradiction before judgment.","dependencies":["FPC-EXECUTE-020","FPC-CROSS-030"],"primary_role":"integrator","court_seat":"integrator","consulted_roles":["curator","steward","advocate"],"required_inputs":[f"{EVIDENCE}/execution.json",f"{EVIDENCE}/execution-transcript.json",f"{EVIDENCE}/cross-examination.json"],"expected_outputs":[f"{EVIDENCE}/integration.json"],"read_scope":[f"{EVIDENCE}/discovery-analysis.json",f"{EVIDENCE}/execution.json",f"{EVIDENCE}/execution-transcript.json",f"{EVIDENCE}/cross-examination.json"],"write_scope":[f"{EVIDENCE}/integration.json"],"required_tests":[f"python {DAG_DIR}/runner.py verify --receipt {EVIDENCE}/integration.json --phase integration"],"acceptance_criteria":["Integration binds all receipt digests and explicitly accepts, rejects, or defers the fixture-only causal predicate.","It grants no implementation or retry authority."],"parallel_safe":False,"semantic_locks":["integration:fpc-causality"],"critical_path_importance":75,"stopping_condition":"One digest-bound integration receipt records conflicts and narrow conclusion.","rollback":"Revert only this integration receipt."},
 {"id":"FPC-JUDGE-050","title":"Judge fixture prerequisite causality appeal","objective":"As a Judge distinct from all prior identities, issue adopt, adapt, defer, reject, or quarantine for the causal predicate only.","rationale":"Only an independent Judge can determine whether a new, separately governed DAG may be proposed.","dependencies":["FPC-INTEGRATE-040"],"primary_role":"orchestrator","court_seat":"judge-distinct-from-all-prior","consulted_roles":["curator","steward","integrator","advocate"],"required_inputs":[f"{EVIDENCE}/integration.json",f"{EVIDENCE}/cross-examination.json",OPENING],"expected_outputs":["evidence/courts/CASE-FIXTURE-PREREQUISITE-CAUSALITY-APPEAL-QUALIFICATION.json"],"read_scope":[f"{EVIDENCE}/discovery-analysis.json",f"{EVIDENCE}/execution.json",f"{EVIDENCE}/execution-transcript.json",f"{EVIDENCE}/cross-examination.json",f"{EVIDENCE}/integration.json",OPENING],"write_scope":["evidence/courts/CASE-FIXTURE-PREREQUISITE-CAUSALITY-APPEAL-QUALIFICATION.json"],"required_tests":[f"python {DAG_DIR}/verify_plan.py"],"acceptance_criteria":["Verdict preserves all dissent and may at most authorize a new separately sealed follow-on proposal.","No verdict promotes fixture/GCO work, makes a performance claim, changes code, or retries knowledge BASELINE-000."],"parallel_safe":False,"semantic_locks":["court:fpc-causality-verdict"],"critical_path_importance":60,"stopping_condition":"Retain one signed, digest-bound disposition with unresolved findings.","rollback":"Revert only final court receipt if correction is separately authorized."},
]
