"""Immutable Appeals-Judge-authorized FPCR v2 contracts."""
from __future__ import annotations

EVALUATED_COMMIT = "b789b68e7d6a741e0b85a3ac33cbce846e1e32c9"
EVALUATED_TREE = "b909b7b7e374bff22912059387ef0fe639498af6"
REJECTED_TUPLES = (
    ("20e26e3c53d41ec4093b23f0957766cd0cbdab70", "f454db6d64120c946ae6700bcf4b4b6ea1bef26c"),
    ("20e26e3c53d41ec4093b23f0957766cd0cbdab70", "4f20bd2"),
)
CLAIMED_DISCOVERY_COUNT = 1059
RUNNER_TIMEOUT_SECONDS = 2700
DAG_DIR = "docs/execution/dags/fixture-prerequisite-causality-reseal-v2"
OPENING = "evidence/courts/CASE-FIXTURE-PREREQUISITE-CAUSALITY-RESEAL-DEFECT.json"
EVIDENCE = "evidence/performance/fixture-prerequisite-causality-reseal-v2"
FROZEN_AUTOPILOT_PLAN = "sha256:85fd0c69fed4aa8cd40019bfeaccc5a686fa408ae5183060ae0320d412cea9ef"

SEAL_OUTPUTS = [
    f"{DAG_DIR}/README.md", f"{DAG_DIR}/.gitignore", f"{DAG_DIR}/specs.py",
    f"{DAG_DIR}/generate_plan.py", f"{DAG_DIR}/verify_plan.py", f"{DAG_DIR}/runner.py",
    f"{DAG_DIR}/manifest.json", OPENING,
]
COMMON_INPUTS = ["AGENTS.md", "docs/execution/DAG_AUTHORING_STANDARD.md", OPENING,
                 "evidence/performance/fixture-prerequisite-causality-appeal-v1/discovery-analysis.json"]

SPECS = [
 {"id":"FPCR-SEAL-000","title":"Seal fixture prerequisite causality reseal defect court","objective":"As Clerk and Architect, seal the corrected-source, no-code appeal before evidence work.","rationale":"The superseded appeal evaluated an invalid commit/tree tuple and cannot unlock further work.","dependencies":[],"primary_role":"orchestrator","court_seat":"clerk-and-architect","consulted_roles":["curator","steward","integrator"],"required_inputs":COMMON_INPUTS,"expected_outputs":SEAL_OUTPUTS,"read_scope":COMMON_INPUTS,"write_scope":SEAL_OUTPUTS,"required_tests":[f"python {DAG_DIR}/verify_plan.py",f"python {DAG_DIR}/runner.py self-test"],"acceptance_criteria":["Exactly six nodes and the required dependency graph compile deterministically.","The source is only b789b68e7d6a741e0b85a3ac33cbce846e1e32c9/b909b7b7e374bff22912059387ef0fe639498af6.","Both known bad tuples are rejected before any discovery or execution."],"parallel_safe":False,"semantic_locks":["contract:fpcr-v2"],"critical_path_importance":100,"stopping_condition":"Commit only the declared eight seal artifacts after all required seal checks pass.","rollback":"Revert only this retained seal commit; preserve prior evidence."},
 {"id":"FPCR-DISCOVERY-010","title":"Independently verify discovery identity","objective":"As independent Explorer and Advocate, independently verify or falsify the claimed 1,059-test discovery against the sole source tuple.","rationale":"The count is a claim, not inherited truth, and no bad tuple may be normalized.","dependencies":["FPCR-SEAL-000"],"primary_role":"explorer","court_seat":"independent-explorer-and-advocate","consulted_roles":["curator","steward"],"required_inputs":[f"{DAG_DIR}/runner.py",OPENING],"expected_outputs":[f"{EVIDENCE}/discovery-analysis.json"],"read_scope":["tests/","pyproject.toml","src/hive_mind_os",OPENING],"write_scope":[f"{EVIDENCE}/discovery-analysis.json"],"required_tests":[f"python {DAG_DIR}/runner.py verify --receipt {EVIDENCE}/discovery-analysis.json --phase discovery"],"acceptance_criteria":["Receipt binds the only valid commit/tree pair.","It independently reports whether 1,059 is reproduced, falsified, or blocked.","No root-CI execution or code/test change occurs."],"parallel_safe":False,"semantic_locks":["evidence:fpcr-discovery"],"critical_path_importance":95,"stopping_condition":"Write one verifier-bound analysis or blocker receipt and stop.","rollback":"Revert only this evidence commit."},
 {"id":"FPCR-EXECUTE-020","title":"Run one hermetic corrected-source root-CI execution","objective":"As independent Curator, execute exactly one serialized hermetic root-CI run against the sole valid source pair.","rationale":"Only one bounded execution can observe the complete causal inventory.","dependencies":["FPCR-DISCOVERY-010"],"primary_role":"curator","court_seat":"independent-execution-curator","consulted_roles":["steward","optimizer"],"required_inputs":[f"{DAG_DIR}/runner.py",f"{EVIDENCE}/discovery-analysis.json"],"expected_outputs":[f"{EVIDENCE}/execution.json",f"{EVIDENCE}/execution-transcript.json"],"read_scope":["tests/","src/hive_mind_os","pyproject.toml",f"{EVIDENCE}/discovery-analysis.json"],"write_scope":[f"{EVIDENCE}/execution.json",f"{EVIDENCE}/execution-transcript.json"],"required_tests":[f"python {DAG_DIR}/runner.py verify --receipt {EVIDENCE}/execution.json --phase execution"],"acceptance_criteria":["Fresh editable venv, PYTHONNOUSERSITE=1, cleared PYTHONPATH, -E -s, source import origin, exact command and one 2700-second budget are recorded.","Transcript retains complete result inventory or explicit timeout/truncation evidence.","No retry, code/test change, cache, network effect, or implementation occurs."],"parallel_safe":True,"semantic_locks":["execution:fpcr-root-ci"],"critical_path_importance":90,"stopping_condition":"One execution and durable transcript are written; never rerun in this node.","rollback":"Revert only this receipt commit."},
 {"id":"FPCR-CROSS-030","title":"Cross-examine corrected-source fixture causality","objective":"As separate Cross-Examiner, challenge source identity, provenance, environment, inventory, timeout, import, and causal conclusions.","rationale":"Adverse evidence must remain independent from the sole execution.","dependencies":["FPCR-DISCOVERY-010"],"primary_role":"curator","court_seat":"cross-examiner-distinct","consulted_roles":["advocate","steward"],"required_inputs":[f"{DAG_DIR}/runner.py",f"{EVIDENCE}/discovery-analysis.json",OPENING],"expected_outputs":[f"{EVIDENCE}/cross-examination.json"],"read_scope":["tests/","src/hive_mind_os",f"{EVIDENCE}/discovery-analysis.json",OPENING],"write_scope":[f"{EVIDENCE}/cross-examination.json"],"required_tests":[f"python {DAG_DIR}/runner.py verify --receipt {EVIDENCE}/cross-examination.json --phase cross"],"acceptance_criteria":["Cross receipt preserves counterclaims for invalid tuple, count mismatch, timeout, contamination, fixture non-causality, and scope.","It does not modify code or use unrecorded execution."],"parallel_safe":True,"semantic_locks":["evidence:fpcr-cross"],"critical_path_importance":85,"stopping_condition":"Record independent adverse findings and stop.","rollback":"Revert only this evidence commit."},
 {"id":"FPCR-INTEGRATE-040","title":"Integrate corrected-source causal evidence","objective":"As Integrator, reconcile discovery, one execution, and cross-examination into a narrow disposition.","rationale":"The court needs agreement or contradiction before judgment.","dependencies":["FPCR-EXECUTE-020","FPCR-CROSS-030"],"primary_role":"integrator","court_seat":"integrator","consulted_roles":["curator","steward","advocate"],"required_inputs":[f"{EVIDENCE}/execution.json",f"{EVIDENCE}/execution-transcript.json",f"{EVIDENCE}/cross-examination.json"],"expected_outputs":[f"{EVIDENCE}/integration.json"],"read_scope":[f"{EVIDENCE}/discovery-analysis.json",f"{EVIDENCE}/execution.json",f"{EVIDENCE}/execution-transcript.json",f"{EVIDENCE}/cross-examination.json"],"write_scope":[f"{EVIDENCE}/integration.json"],"required_tests":[f"python {DAG_DIR}/runner.py verify --receipt {EVIDENCE}/integration.json --phase integration"],"acceptance_criteria":["Integration binds all receipt digests and explicitly accepts, rejects, or defers the causal predicate.","It grants no implementation, performance, GCO, baseline, or original-node authority."],"parallel_safe":False,"semantic_locks":["integration:fpcr-causality"],"critical_path_importance":75,"stopping_condition":"One digest-bound integration receipt records conflicts and narrow conclusion.","rollback":"Revert only this integration receipt."},
 {"id":"FPCR-JUDGE-050","title":"Judge corrected-source fixture causality appeal","objective":"As Judge distinct from all prior identities, issue adopt, adapt, defer, reject, or quarantine for the causal predicate only.","rationale":"Only a distinct Judge can authorize a separately governed follow-on proposal.","dependencies":["FPCR-INTEGRATE-040"],"primary_role":"orchestrator","court_seat":"judge-distinct-from-all-prior","consulted_roles":["curator","steward","integrator","advocate"],"required_inputs":[f"{EVIDENCE}/integration.json",f"{EVIDENCE}/cross-examination.json",OPENING],"expected_outputs":["evidence/courts/CASE-FIXTURE-PREREQUISITE-CAUSALITY-RESEAL-QUALIFICATION.json"],"read_scope":[f"{EVIDENCE}/discovery-analysis.json",f"{EVIDENCE}/execution.json",f"{EVIDENCE}/execution-transcript.json",f"{EVIDENCE}/cross-examination.json",f"{EVIDENCE}/integration.json",OPENING],"write_scope":["evidence/courts/CASE-FIXTURE-PREREQUISITE-CAUSALITY-RESEAL-QUALIFICATION.json"],"required_tests":[f"python {DAG_DIR}/verify_plan.py"],"acceptance_criteria":["Verdict preserves all dissent and may at most authorize a separately sealed follow-on proposal.","No verdict unlocks an original FPC node, promotes fixture/GCO work, makes performance claim, changes code, or retries knowledge BASELINE-000."],"parallel_safe":False,"semantic_locks":["court:fpcr-v2-verdict"],"critical_path_importance":60,"stopping_condition":"Retain one signed, digest-bound disposition with unresolved findings.","rollback":"Revert only final court receipt if separately authorized."},
]
