from __future__ import annotations

import json
import math
from copy import deepcopy
from importlib.resources import files
from typing import Any, Mapping, cast

from .builder_playbook import compile_builder_implementation, example_builder_request
from .builder_playbook_contracts import OUTPUT_FIELDS as BUILDER_OUTPUT_FIELDS
from .builder_playbook_contracts import validate_builder
from .canonical import canonical_bytes, digest, reject_private_content
from .contracts import validate_foundation
from .curator_playbook_contracts import (
    AGENT_ID,
    BASE_DEFINITION_ID,
    COURT_ROLES,
    CURATOR_SCHEMA_NAMES,
    DEFINITION_ID,
    EXPECTED_SUCCESSOR_DIGEST,
    LAYER_IDS,
    LAYER_KINDS,
    OUTPUT_FIELDS,
    OUTPUT_SCHEMA_BY_FIELD,
    RESOURCE_AXES,
    RESOURCE_SECTIONS,
    validate_curator,
)
from .generation import GENERATOR_VERSION, compile_generation_zero_candidates, verify_generated_candidates

MAX_TEXT = 16_000
MAX_NESTED_VALUES = 20_000
MAX_CLAIMS = 128
MAX_EVIDENCE = 256
MAX_SOURCES = 128
MAX_CHECKS = 128
MAX_REGRESSION_TARGETS = 128

BASE_CANONICAL_FILE_DIGEST = "sha256:e9b12bce0b6b8ebabb117309bd9a05390bf470ee4fd473eddd61ed0636a4860c"
BASE_PROJECTION_DIGEST = "sha256:ffa45a3bea2edecd008c2b4788ff9ecf8cec66620fd293a77b980ea2de7ea312"
BASE_CONTENT_DIGEST = "sha256:bd4927453a1b71e5be3b97eb0e8f03a99d4356669d42661ba4b45cabf5ebe398"
BASE_PROMPT_DIGEST = "sha256:86815af7cf7cf2ab80a7ce9712ca350984c7c029e150175ca480339a656eaa5b"
BUILTIN_AGENT_DIGEST = "sha256:4bfc6dbac52a70ba05e24cefd26b08ee4e0949e6d6e82b803d1e9938b91130c6"
BUILTIN_PROMPT_DIGEST = "sha256:646d47db0a81705c21451c53c43aba517cdf57261c8e26b3862642d3180afa1e"
BUILTIN_SKILL_DIGEST = "sha256:0dbe50c8d73eb510d853c19b03233dd60577c7eee8ae4ecea085a8caef33dc52"
BUILTIN_SKILL_INSTRUCTION_DIGEST = "sha256:0f26c0723bccce3d98fbb54de3795b58dbce215e5aa8c4a58c7a605c84ec344a"


class CuratorContractError(ValueError):
    pass


def digest_bytes(value: bytes) -> str:
    from hashlib import sha256

    return f"sha256:{sha256(value).hexdigest()}"


def _read_builtin_json(path: tuple[str, ...], expected_digest: str) -> dict[str, Any]:
    raw = files("hive_mind_os").joinpath("builtin_packages", "hive-core", *path).read_bytes()
    if digest_bytes(raw) != expected_digest:
        raise ValueError(f"packaged {'/'.join(path)} bytes drifted")
    document = json.loads(raw)
    if type(document) is not dict:
        raise ValueError(f"packaged {'/'.join(path)} is not an object")
    return document


def _verify_packaged_phase2_bytes(generated: dict[str, bytes]) -> None:
    foundation = files("hive_mind_os.foundation")
    canonical = foundation.joinpath("canonical", "agents", "curator.json").read_bytes()
    if digest_bytes(canonical) != BASE_CANONICAL_FILE_DIGEST:
        raise ValueError("packaged Phase 2 Curator canonical bytes drifted")
    generated_root = foundation.joinpath("generated")
    observed = {
        "manifest.json": generated_root.joinpath("manifest.json").read_bytes(),
        **{
            path: generated_root.joinpath(*path.split("/")).read_bytes()
            for path in generated
            if path != "manifest.json"
        },
    }
    issues = verify_generated_candidates(observed, expected_paths=generated)
    if issues:
        raise ValueError("packaged Phase 2 generated bytes drifted: " + "; ".join(issues))


def _layer(
    position: int,
    layer_id: str,
    kind: str,
    version: str,
    source_digests: list[str],
) -> dict[str, Any]:
    body = {
        "position": position,
        "layer_id": layer_id,
        "kind": kind,
        "version": version,
        "source_digests": source_digests,
    }
    return {**body, "digest": digest(body)}


def _compile_unpinned_successor() -> dict[str, Any]:
    generated = compile_generation_zero_candidates()
    _verify_packaged_phase2_bytes(generated)
    curator_bytes = generated["agents/curator.json"]
    curator = json.loads(curator_bytes)
    if not validate_foundation("agent-definition-v2", curator).valid:
        raise ValueError("Phase 2 Curator projection is contract-invalid")
    if (
        curator["definition_id"] != BASE_DEFINITION_ID
        or curator["content_digest"] != BASE_CONTENT_DIGEST
        or curator["generator_version"] != GENERATOR_VERSION
        or digest_bytes(curator_bytes) != BASE_PROJECTION_DIGEST
    ):
        raise ValueError("Phase 2 Curator identity or projection drifted")
    prompt_layers = curator["prompt_layers"]
    if (
        len(prompt_layers) != 1
        or prompt_layers[0]["layer_id"] != "generation-zero:curator"
        or prompt_layers[0]["version"] != "1"
        or prompt_layers[0]["digest"] != BASE_PROMPT_DIGEST
    ):
        raise ValueError("Generation Zero Curator prompt binding drifted")

    builtin_agent = _read_builtin_json(("agents", "curator.json"), BUILTIN_AGENT_DIGEST)
    _read_builtin_json(("prompts", "curator.json"), BUILTIN_PROMPT_DIGEST)
    builtin_skill = _read_builtin_json(("skills", "curator.json"), BUILTIN_SKILL_DIGEST)
    builtin_instruction = _read_builtin_json(
        ("skills", "instructions", "curator.json"),
        BUILTIN_SKILL_INSTRUCTION_DIGEST,
    )
    if builtin_agent.get("role_binding") != "curator":
        raise ValueError("built-in Curator role binding drifted")
    if builtin_skill.get("component_id") != "skill.curator":
        raise ValueError("built-in Curator skill identity drifted")

    playbook = {
        "purpose": "Independently reconstruct and hostilely verify material claims without implementation or approval authority.",
        "responsibilities": [
            "verification-scope",
            "claim-reconstruction",
            "clean-boundary-reproduction",
            "counterexample-search",
            "security-privacy-review",
            "provenance-license-review",
            "regression-analysis",
            "artifact-receipt-verification",
            "rollback-verification",
            "release-recommendation",
            "dissent-and-unresolved-evidence",
        ],
        "non_goals": [
            "candidate-implementation",
            "self-verification",
            "self-approval",
            "release-authority",
            "promotion-authority",
            "runtime-execution",
        ],
        "fail_closed_on": [
            "false-green-builder-evidence",
            "same-identity-verification",
            "forged-receipt",
            "stale-evidence",
            "point-in-time-leakage",
            "test-weakening",
            "source-or-license-gap",
            "unsupported-completion-claim",
            "cross-tenant-or-cross-repository-substitution",
        ],
        "limits": {
            "max_claims": MAX_CLAIMS,
            "max_evidence_items": MAX_EVIDENCE,
            "max_sources": MAX_SOURCES,
            "max_checks": MAX_CHECKS,
            "max_regression_targets": MAX_REGRESSION_TARGETS,
        },
    }
    lifecycle = {
        "predecessor": "builder",
        "successor": "integrator",
        "blind_first": True,
        "clean_boundary_required": True,
        "authenticated_independence_required_for_release": True,
        "procedural_simulation_is_independent": False,
    }
    layers = [
        _layer(1, LAYER_IDS[0], LAYER_KINDS[0], "2-candidate", [BASE_PROJECTION_DIGEST]),
        _layer(2, LAYER_IDS[1], LAYER_KINDS[1], "1", [BASE_PROMPT_DIGEST]),
        _layer(3, LAYER_IDS[2], LAYER_KINDS[2], "1", [digest(playbook)]),
        _layer(4, LAYER_IDS[3], LAYER_KINDS[3], "1", [BUILTIN_SKILL_DIGEST, BUILTIN_SKILL_INSTRUCTION_DIGEST]),
        _layer(5, LAYER_IDS[4], LAYER_KINDS[4], "1", [digest(CURATOR_SCHEMA_NAMES)]),
        _layer(6, LAYER_IDS[5], LAYER_KINDS[5], "1", [digest(OUTPUT_FIELDS)]),
        _layer(7, LAYER_IDS[6], LAYER_KINDS[6], "1", [digest({"authority": "none", "activation": "inert"})]),
        _layer(8, LAYER_IDS[7], LAYER_KINDS[7], "1", [digest(lifecycle)]),
    ]
    body = {
        "record_type": "curator-agent-successor",
        "schema_version": 1,
        "agent_id": AGENT_ID,
        "definition_id": DEFINITION_ID,
        "base_definition_id": BASE_DEFINITION_ID,
        "role_id": "curator",
        "version": "2-shadow-1",
        "mission": curator["mission"],
        "layers": layers,
        "output_contract_refs": [OUTPUT_SCHEMA_BY_FIELD[field] for field in OUTPUT_FIELDS],
        "effective_capabilities": [],
        "tool_refs": [],
        "activation": "inert",
        "authority": "none",
        "public": False,
        "implementation_authorized": False,
        "execution_authorized": False,
        "test_result_authorized": False,
        "completion_authorized": False,
        "release_authorized": False,
        "approval_authorized": False,
        "promotion_authorized": False,
    }
    candidate = {**body, "content_digest": digest(body)}
    validation = validate_curator(
        "curator-agent-successor-v1",
        candidate,
        enforce_reviewed_successor=False,
    )
    if not validation.valid:
        raise ValueError("Curator successor failed its contract: " + "; ".join(validation.issues))
    return candidate


def compile_curator_successor() -> dict[str, Any]:
    candidate = _compile_unpinned_successor()
    if candidate["content_digest"] != EXPECTED_SUCCESSOR_DIGEST:
        raise ValueError("Curator successor differs from its reviewed digest")
    return deepcopy(candidate)


def curator_successor_bytes() -> bytes:
    return canonical_bytes(compile_curator_successor())


def _strict_json_copy(
    value: Any,
    *,
    path: str = "$",
    depth: int = 0,
    counter: list[int] | None = None,
) -> Any:
    if counter is None:
        counter = [0]
    counter[0] += 1
    if counter[0] > MAX_NESTED_VALUES:
        raise CuratorContractError("request exceeds bounded nested-value limit")
    if depth > 24:
        raise CuratorContractError("request exceeds bounded nesting depth")
    if value is None or type(value) in {bool, int}:
        return value
    if type(value) is float:
        if not math.isfinite(value):
            raise CuratorContractError(f"{path} contains a non-finite number")
        return value
    if type(value) is str:
        if len(value) > MAX_TEXT:
            raise CuratorContractError(f"{path} exceeds bounded text limit")
        return value
    if type(value) is list:
        return [
            _strict_json_copy(item, path=f"{path}[{index}]", depth=depth + 1, counter=counter)
            for index, item in enumerate(value)
        ]
    if type(value) is dict:
        copied: dict[str, Any] = {}
        for key, item in value.items():
            if type(key) is not str:
                raise CuratorContractError(f"{path} contains a non-string key")
            copied[key] = _strict_json_copy(
                item,
                path=f"{path}.{key}",
                depth=depth + 1,
                counter=counter,
            )
        return copied
    raise CuratorContractError(f"{path} contains unsupported type {type(value).__name__}")


def _unique_ids(values: list[Mapping[str, Any]], field: str, label: str) -> list[str]:
    identifiers = [str(item[field]) for item in values]
    if len(identifiers) != len(set(identifiers)):
        raise CuratorContractError(f"duplicate {label} identifier")
    return identifiers


def _require_subset(values: list[str], admitted: set[str], label: str) -> None:
    unknown = sorted(set(values) - admitted)
    if unknown:
        raise CuratorContractError(f"{label} references unknown identifiers: {', '.join(unknown)}")


def _current_fingerprint(request: Mapping[str, Any]) -> str:
    return digest(
        {
            "objective_id": request["objective_id"],
            "subject_commit": request["subject_commit"],
            "subject_tree": request["subject_tree"],
            "claims": [
                {
                    "claim_id": item["claim_id"],
                    "claim_type": item["claim_type"],
                    "evidence": sorted(item["builder_evidence_refs"]),
                }
                for item in sorted(request["claims"], key=lambda item: item["claim_id"])
            ],
            "checks": [
                {
                    "check_id": item["check_id"],
                    "command": item["command"],
                    "expected": item["expected"],
                }
                for item in sorted(request["sealed_checks"], key=lambda item: item["check_id"])
            ],
        }
    )


def _normalized_builder_envelope(value: Mapping[str, Any]) -> dict[str, Any]:
    normalized = deepcopy(value)
    outputs = normalized.get("outputs")
    if isinstance(outputs, Mapping):
        normalized["outputs"] = {
            field: deepcopy(outputs[field])
            for field in BUILDER_OUTPUT_FIELDS
            if field in outputs
        }
    return normalized


def _validate_request_semantics(request: dict[str, Any]) -> None:
    try:
        reject_private_content(request)
    except ValueError as error:
        raise CuratorContractError(str(error)) from error

    builder = _normalized_builder_envelope(request["builder_envelope"])
    builder_validation = validate_builder("builder-implementation-envelope-v1", builder)
    if not builder_validation.valid:
        raise CuratorContractError(
            "Builder envelope is invalid: " + "; ".join(builder_validation.issues)
        )
    if (
        builder["tenant_id"] != request["tenant_id"]
        or builder["repository_id"] != request["repository_id"]
    ):
        raise CuratorContractError("Builder envelope scope differs from Curator request")
    builder_scope = builder["request_snapshot"]["scope"]
    if (
        builder_scope["subject_commit"] != request["subject_commit"]
        or builder_scope["subject_tree"] != request["subject_tree"]
    ):
        raise CuratorContractError("Builder subject differs from Curator request")
    handoff = builder["outputs"]["curator_handoff"]
    if (
        handoff["next_role"] != "curator"
        or handoff["independent_reconstruction_required"] is not True
    ):
        raise CuratorContractError("Builder did not produce the required Curator handoff")

    builder_identity = request["builder_identity"]
    curator_identity = request["curator_identity"]
    if builder_identity["role"] != "builder" or curator_identity["role"] != "curator":
        raise CuratorContractError("verification identities have incorrect roles")
    if builder_identity["actor_id"] == curator_identity["actor_id"]:
        raise CuratorContractError("Curator cannot verify the Builder under the same identity")
    if request["blind_seal_sequence"] >= request["candidate_access_sequence"]:
        raise CuratorContractError("blind verification checks were not sealed before candidate access")

    acceptance_ids = set(_unique_ids(request["acceptance_criteria"], "acceptance_id", "acceptance"))
    claims = request["claims"]
    claim_ids = set(_unique_ids(claims, "claim_id", "claim"))
    checks = request["sealed_checks"]
    _unique_ids(checks, "check_id", "sealed check")
    evidence = request["observed_evidence"]
    evidence_ids = set(_unique_ids(evidence, "evidence_id", "evidence"))
    sources = request["sources"]
    source_ids = set(_unique_ids(sources, "source_id", "source"))
    targets = request["regression_targets"]
    _unique_ids(targets, "target_id", "regression target")

    for claim in claims:
        _require_subset(claim["acceptance_refs"], acceptance_ids, f"claim {claim['claim_id']} acceptance")
        _require_subset(claim["builder_evidence_refs"], evidence_ids, f"claim {claim['claim_id']} evidence")
        _require_subset(claim["source_refs"], source_ids, f"claim {claim['claim_id']} sources")
    covered_acceptance = {ref for claim in claims for ref in claim["acceptance_refs"]}
    if covered_acceptance != acceptance_ids:
        raise CuratorContractError("claims do not cover every acceptance criterion")

    for check in checks:
        _require_subset(check["claim_refs"], claim_ids, f"check {check['check_id']} claims")
        _require_subset(check["acceptance_refs"], acceptance_ids, f"check {check['check_id']} acceptance")
        if check["sealed_before_candidate_access"] is not True:
            raise CuratorContractError("unsealed check cannot become verification evidence")
    checked_claims = {ref for check in checks for ref in check["claim_refs"]}
    if checked_claims != claim_ids:
        raise CuratorContractError("sealed checks do not cover every material claim")

    required_receipt_fields = {
        "command",
        "exit_code",
        "started_at",
        "finished_at",
        "stdout_digest",
        "stderr_digest",
        "subject_commit",
        "subject_tree",
    }
    for item in evidence:
        _require_subset(item["claim_refs"], claim_ids, f"evidence {item['evidence_id']} claims")
        _require_subset(item["acceptance_refs"], acceptance_ids, f"evidence {item['evidence_id']} acceptance")
        if item["integrity_status"] != "digest-verified":
            raise CuratorContractError(f"evidence {item['evidence_id']} is forged or unverifiable")
        if item["stale"] is not False:
            raise CuratorContractError(f"evidence {item['evidence_id']} is stale")
        if item["subject_commit"] not in {request["base_commit"], request["subject_commit"]}:
            raise CuratorContractError(f"evidence {item['evidence_id']} leaks a future or foreign commit")
        if item["subject_tree"] not in {request["base_tree"], request["subject_tree"]}:
            raise CuratorContractError(f"evidence {item['evidence_id']} has a foreign tree")
        if item["kind"] in {"test-before", "test-after", "security", "privacy", "rollback"}:
            if item["producer_role"] == "builder":
                raise CuratorContractError(
                    f"evidence {item['evidence_id']} is Builder self-verification"
                )
            if not required_receipt_fields.issubset(set(item["receipt_fields"])):
                raise CuratorContractError(
                    f"evidence {item['evidence_id']} lacks complete receipt fields"
                )
    covered_evidence = {ref for claim in claims for ref in claim["builder_evidence_refs"]}
    if not covered_evidence.issubset(evidence_ids):
        raise CuratorContractError("claims reference unavailable evidence")

    material_claim_ids = {claim["claim_id"] for claim in claims if claim["material"]}
    for source in sources:
        _require_subset(source["claim_refs"], claim_ids, f"source {source['source_id']} claims")
        if material_claim_ids.intersection(source["claim_refs"]):
            if source["license_status"] != "admitted" or source["completeness"] != "complete":
                raise CuratorContractError(
                    f"source {source['source_id']} cannot support material claims"
                )
    sourced_material = {
        ref
        for source in sources
        if source["license_status"] == "admitted" and source["completeness"] == "complete"
        for ref in source["claim_refs"]
    }
    if not material_claim_ids.issubset(sourced_material):
        raise CuratorContractError("material claims have source or license gaps")

    for target in targets:
        if target["assertions_after"] < target["assertions_before"]:
            raise CuratorContractError(f"regression target {target['target_id']} weakens assertions")
        if target["test_functions_after"] < target["test_functions_before"]:
            raise CuratorContractError(f"regression target {target['target_id']} removes tests")

    point_in_time = request["point_in_time"]
    if point_in_time["target_commit"] != request["subject_commit"]:
        raise CuratorContractError("point-in-time target differs from subject commit")
    if point_in_time["knowledge_cutoff_commit"] not in {
        request["base_commit"],
        request["subject_commit"],
    }:
        raise CuratorContractError("point-in-time knowledge cutoff is foreign")
    if point_in_time["future_commit_refs"]:
        raise CuratorContractError("future commit knowledge is prohibited")

    actor_roles = [item["role"] for item in request["actors"]]
    actor_ids = [item["actor_id"] for item in request["actors"]]
    if tuple(actor_roles) != COURT_ROLES:
        raise CuratorContractError("procedural role catalog is incomplete or reordered")
    if len(actor_ids) != len(set(actor_ids)):
        raise CuratorContractError("procedural actor identifiers must be unique")
    if any(item["authenticated"] is not False for item in request["actors"]):
        raise CuratorContractError("caller cannot manufacture authenticated actors")

    budget_values = list(request["budgets"].values())
    reserves = [
        request["verification_reserve_ppm"],
        request["evidence_reserve_ppm"],
        request["rollback_reserve_ppm"],
    ]
    known = all(type(value) is int for value in budget_values)
    unknown = all(value is None for value in budget_values)
    if not (known or unknown):
        raise CuratorContractError("resource axes must be wholly known or wholly unknown")
    if known:
        if not all(type(value) is int and value > 0 for value in reserves):
            raise CuratorContractError("known resources require positive reserves")
        if sum(cast(int, value) for value in reserves) >= 1_000_000:
            raise CuratorContractError("resource reserves consume the full budget")
    elif any(value is not None for value in reserves):
        raise CuratorContractError("unknown resources cannot manufacture reserves")

    if any(value is not False for value in request["caller_claims"].values()):
        raise CuratorContractError("caller cannot assert completion, passing tests, release, or independence")
    current = _current_fingerprint(request)
    if current in request["prior_fingerprints"]:
        raise CuratorContractError("verification request repeats a prior semantic fingerprint")


def _validated_request(request: Mapping[str, Any]) -> dict[str, Any]:
    if type(request) is not dict:
        raise CuratorContractError("Curator request must be an exact built-in object")
    copied = _strict_json_copy(request)
    validation = validate_curator("curator-verification-request-v1", copied)
    if not validation.valid:
        raise CuratorContractError("Curator request is invalid: " + "; ".join(validation.issues))
    _validate_request_semantics(copied)
    return copied


def _budget_state(request: Mapping[str, Any]) -> str:
    return "known" if all(type(value) is int for value in request["budgets"].values()) else "unknown"


def _authority_state() -> dict[str, Any]:
    return {
        "authority": "none",
        "activation": "inert",
        "effective_capability_count": 0,
        "tool_count": 0,
        "implementation_authorized": False,
        "execution_authorized": False,
        "test_result_authorized": False,
        "completion_authorized": False,
        "release_authorized": False,
        "promotion_authorized": False,
    }


def _output_scope(request: Mapping[str, Any], request_digest: str) -> dict[str, Any]:
    builder = request["builder_envelope"]
    return {
        "request_id": request["request_id"],
        "request_digest": request_digest,
        "objective_id": request["objective_id"],
        "tenant_id": request["tenant_id"],
        "repository_id": request["repository_id"],
        "curator_definition_id": DEFINITION_ID,
        "curator_version": "2-shadow-1",
        "builder_definition_id": "hive-agent-definition:builder:v2-shadow-1",
        "builder_successor_digest": builder["successor_digest"],
        "builder_implementation_digest": builder["implementation_digest"],
        "base_commit": request["base_commit"],
        "base_tree": request["base_tree"],
        "subject_commit": request["subject_commit"],
        "subject_tree": request["subject_tree"],
        "claim_refs": sorted(item["claim_id"] for item in request["claims"]),
        "acceptance_refs": sorted(
            item["acceptance_id"] for item in request["acceptance_criteria"]
        ),
        "evidence_refs": sorted(
            item["evidence_id"] for item in request["observed_evidence"]
        ),
        "rollback_refs": sorted(request["rollback_refs"]),
        "authority_state": _authority_state(),
        "budget_state": _budget_state(request),
        "authenticated_distinct_actors": False,
        "same_assistant_performed_procedural_passes": True,
        "independence_claimed": False,
    }


def _with_output_digest(body: dict[str, Any]) -> dict[str, Any]:
    return {**body, "output_digest": digest(body)}


def _verification_scope(request: Mapping[str, Any], request_digest: str) -> dict[str, Any]:
    return _with_output_digest(
        {
            "record_type": "curator-verification-scope",
            "schema_version": 1,
            **_output_scope(request, request_digest),
            "blind_checks_sealed": True,
            "sealed_before_candidate_access": True,
            "clean_boundary_required": True,
            "builder_summary_is_proof": False,
            "implementation_authorized": False,
            "verification_scope_complete": True,
        }
    )


def _claim_reconstruction(request: Mapping[str, Any], request_digest: str) -> dict[str, Any]:
    claims = [
        {
            "claim_id": claim["claim_id"],
            "statement_digest": digest(claim["statement"]),
            "claim_type": claim["claim_type"],
            "material": claim["material"],
            "acceptance_refs": sorted(claim["acceptance_refs"]),
            "source_refs": sorted(claim["source_refs"]),
            "builder_evidence_refs": sorted(claim["builder_evidence_refs"]),
            "reconstructed_without_builder_rationale": True,
        }
        for claim in sorted(request["claims"], key=lambda item: item["claim_id"])
    ]
    return _with_output_digest(
        {
            "record_type": "curator-claim-reconstruction",
            "schema_version": 1,
            **_output_scope(request, request_digest),
            "claims": claims,
            "complete": True,
            "self_verification_detected": False,
        }
    )


def _clean_boundary_reproduction(request: Mapping[str, Any], request_digest: str) -> dict[str, Any]:
    return _with_output_digest(
        {
            "record_type": "curator-clean-boundary-reproduction",
            "schema_version": 1,
            **_output_scope(request, request_digest),
            "sealed_check_refs": sorted(item["check_id"] for item in request["sealed_checks"]),
            "reproduction_status": "planned-not-executed",
            "commands_executed_by_playbook": False,
            "test_results_authorized": False,
            "fresh_workspace_required": True,
        }
    )


def _counterexample_search(request: Mapping[str, Any], request_digest: str) -> dict[str, Any]:
    categories = (
        "false-green",
        "self-verification",
        "forged-receipt",
        "stale-evidence",
        "point-in-time-leakage",
        "test-weakening",
        "source-license-gap",
        "unsupported-completion",
        "scope-substitution",
    )
    claim_refs = sorted(item["claim_id"] for item in request["claims"])
    evidence_refs = sorted(item["evidence_id"] for item in request["observed_evidence"])
    attacks = [
        {
            "attack_id": f"attack:{category}",
            "category": category,
            "target_refs": claim_refs,
            "required_evidence_refs": evidence_refs,
            "status": "required",
        }
        for category in categories
    ]
    return _with_output_digest(
        {
            "record_type": "curator-counterexample-search",
            "schema_version": 1,
            **_output_scope(request, request_digest),
            "attacks": attacks,
            "coverage_complete": True,
            "counterexamples_executed_by_playbook": False,
        }
    )


def _security_privacy_review(request: Mapping[str, Any], request_digest: str) -> dict[str, Any]:
    evidence_refs = sorted(item["evidence_id"] for item in request["observed_evidence"])
    findings = [
        {
            "finding_id": "finding:private-content-boundary",
            "status": "pass",
            "severity": "major",
            "reason": "The request contains no prohibited private-content fields.",
            "evidence_refs": evidence_refs,
        },
        {
            "finding_id": "finding:sast",
            "status": "not-evaluated",
            "severity": "info",
            "reason": "The inert playbook does not execute a SAST scanner; external CI receipts remain required.",
            "evidence_refs": [],
        },
    ]
    return _with_output_digest(
        {
            "record_type": "curator-security-privacy-review",
            "schema_version": 1,
            **_output_scope(request, request_digest),
            "findings": findings,
            "sast_status": "not-evaluated",
            "private_content_exposed": False,
            "security_approval_authorized": False,
        }
    )


def _provenance_license_review(request: Mapping[str, Any], request_digest: str) -> dict[str, Any]:
    sources = [
        {
            "source_id": source["source_id"],
            "digest": source["digest"],
            "license_status": source["license_status"],
            "completeness": source["completeness"],
            "claim_refs": sorted(source["claim_refs"]),
            "admitted_for_material_claims": (
                source["license_status"] == "admitted"
                and source["completeness"] == "complete"
            ),
        }
        for source in sorted(request["sources"], key=lambda item: item["source_id"])
    ]
    return _with_output_digest(
        {
            "record_type": "curator-provenance-license-review",
            "schema_version": 1,
            **_output_scope(request, request_digest),
            "sources": sources,
            "material_claims_fully_sourced": True,
            "license_gaps": [],
            "provenance_approval_authorized": False,
        }
    )


def _regression_analysis(request: Mapping[str, Any], request_digest: str) -> dict[str, Any]:
    targets = [
        {
            "target_id": target["target_id"],
            "path": target["path"],
            "baseline_digest": target["baseline_digest"],
            "candidate_digest": target["candidate_digest"],
            "test_refs": sorted(target["test_refs"]),
            "assertion_delta": target["assertions_after"] - target["assertions_before"],
            "test_function_delta": target["test_functions_after"] - target["test_functions_before"],
            "weakened": False,
        }
        for target in sorted(request["regression_targets"], key=lambda item: item["target_id"])
    ]
    return _with_output_digest(
        {
            "record_type": "curator-regression-analysis",
            "schema_version": 1,
            **_output_scope(request, request_digest),
            "targets": targets,
            "tests_weakened": False,
            "regression_clearance_authorized": False,
        }
    )


def _artifact_receipt_verification(request: Mapping[str, Any], request_digest: str) -> dict[str, Any]:
    required = {
        "command",
        "exit_code",
        "started_at",
        "finished_at",
        "stdout_digest",
        "stderr_digest",
        "subject_commit",
        "subject_tree",
    }
    evidence = [
        {
            "evidence_id": item["evidence_id"],
            "kind": item["kind"],
            "digest": item["digest"],
            "integrity_status": item["integrity_status"],
            "stale": item["stale"],
            "producer_role": item["producer_role"],
            "receipt_fields_complete": required.issubset(set(item["receipt_fields"])),
        }
        for item in sorted(request["observed_evidence"], key=lambda item: item["evidence_id"])
    ]
    return _with_output_digest(
        {
            "record_type": "curator-artifact-receipt-verification",
            "schema_version": 1,
            **_output_scope(request, request_digest),
            "evidence": evidence,
            "all_digests_verified": True,
            "all_receipt_fields_present": True,
            "artifacts_created_by_playbook": False,
            "verification_authorized": False,
        }
    )


def _rollback_verification(request: Mapping[str, Any], request_digest: str) -> dict[str, Any]:
    return _with_output_digest(
        {
            "record_type": "curator-rollback-verification",
            "schema_version": 1,
            **_output_scope(request, request_digest),
            "rollback_verification_test_refs": sorted(request["rollback_verification_test_refs"]),
            "rollback_required": True,
            "rollback_executed_by_playbook": False,
            "rollback_verified_by_playbook": False,
            "rollback_authorized": False,
        }
    )


def _release_recommendation(request: Mapping[str, Any], request_digest: str) -> dict[str, Any]:
    requested = request["requested_release_recommendation"]
    recommendation = "defer"
    return _with_output_digest(
        {
            "record_type": "curator-release-recommendation",
            "schema_version": 1,
            **_output_scope(request, request_digest),
            "structural_status": "pass",
            "recommendation": recommendation,
            "requested_recommendation": requested,
            "requested_recommendation_eligible": requested == recommendation,
            "reason": "authenticated-independent-verification-and-external-execution-receipts-remain-unavailable",
            "release_ready": False,
            "release_authorized": False,
            "approval_authorized": False,
        }
    )


def _dissent_unresolved_evidence(request: Mapping[str, Any], request_digest: str) -> dict[str, Any]:
    unresolved = [
        {
            "issue_id": "unresolved:authenticated-independence",
            "category": "identity",
            "reason": "Procedural role separation is not externally authenticated independence.",
            "blocking": True,
            "required_evidence_refs": ["evidence:authenticated-curator-identity"],
        },
        {
            "issue_id": "unresolved:real-execution-receipts",
            "category": "execution",
            "reason": "The inert playbook plans reproduction but does not execute commands or create receipts.",
            "blocking": True,
            "required_evidence_refs": ["evidence:external-execution-receipts"],
        },
        {
            "issue_id": "unresolved:release-court",
            "category": "release",
            "reason": "P14-P20 and the independent release-readiness court remain separate obligations.",
            "blocking": True,
            "required_evidence_refs": ["evidence:p20-release-readiness-court"],
        },
    ]
    return _with_output_digest(
        {
            "record_type": "curator-dissent-unresolved-evidence",
            "schema_version": 1,
            **_output_scope(request, request_digest),
            "unresolved": unresolved,
            "dissent_preserved": True,
            "missing_evidence_is_permission": False,
        }
    )


def _allocate_axis(
    ceiling: int | None,
    verification_ppm: int | None,
    evidence_ppm: int | None,
    rollback_ppm: int | None,
) -> dict[str, Any]:
    if ceiling is None:
        return {
            "ceiling": None,
            "verification_reserve": None,
            "evidence_reserve": None,
            "rollback_reserve": None,
            "section_allocations": {section: None for section in RESOURCE_SECTIONS},
        }
    if not all(type(value) is int for value in (verification_ppm, evidence_ppm, rollback_ppm)):
        raise CuratorContractError("known budget lacks reserve percentages")
    verification_rate = cast(int, verification_ppm)
    evidence_rate = cast(int, evidence_ppm)
    rollback_rate = cast(int, rollback_ppm)
    verification = max(1, ceiling * verification_rate // 1_000_000)
    evidence = max(1, ceiling * evidence_rate // 1_000_000)
    rollback = max(1, ceiling * rollback_rate // 1_000_000)
    remaining = ceiling - verification - evidence - rollback
    if remaining < len(RESOURCE_SECTIONS):
        raise CuratorContractError("known budget cannot fund all Curator sections")
    base, remainder = divmod(remaining, len(RESOURCE_SECTIONS))
    allocations = {
        section: base + (1 if index < remainder else 0)
        for index, section in enumerate(RESOURCE_SECTIONS)
    }
    return {
        "ceiling": ceiling,
        "verification_reserve": verification,
        "evidence_reserve": evidence,
        "rollback_reserve": rollback,
        "section_allocations": allocations,
    }


def _resource_accounting(request: Mapping[str, Any]) -> dict[str, Any]:
    state = _budget_state(request)
    return {
        "accounting_status": state,
        "lease_status": "not-issued",
        "axes": {
            axis: _allocate_axis(
                request["budgets"][axis],
                request["verification_reserve_ppm"],
                request["evidence_reserve_ppm"],
                request["rollback_reserve_ppm"],
            )
            for axis in RESOURCE_AXES
        },
        "budget_authorized": False,
    }


def compile_curator_verification(request: Mapping[str, Any]) -> dict[str, Any]:
    copied = _validated_request(request)
    successor = compile_curator_successor()
    request_digest = digest(copied)
    resource = _resource_accounting(copied)
    outputs = {
        "verification_scope": _verification_scope(copied, request_digest),
        "claim_reconstruction": _claim_reconstruction(copied, request_digest),
        "clean_boundary_reproduction": _clean_boundary_reproduction(copied, request_digest),
        "counterexample_search": _counterexample_search(copied, request_digest),
        "security_privacy_review": _security_privacy_review(copied, request_digest),
        "provenance_license_review": _provenance_license_review(copied, request_digest),
        "regression_analysis": _regression_analysis(copied, request_digest),
        "artifact_receipt_verification": _artifact_receipt_verification(copied, request_digest),
        "rollback_verification": _rollback_verification(copied, request_digest),
        "release_recommendation": _release_recommendation(copied, request_digest),
        "dissent_unresolved_evidence": _dissent_unresolved_evidence(copied, request_digest),
    }
    body = {
        "record_type": "curator-verification-envelope",
        "schema_version": 1,
        "request_id": copied["request_id"],
        "objective_id": copied["objective_id"],
        "tenant_id": copied["tenant_id"],
        "repository_id": copied["repository_id"],
        "successor_digest": successor["content_digest"],
        "request_digest": request_digest,
        "request_snapshot": deepcopy(copied),
        "outputs": outputs,
        "resource_accounting": resource,
        "activation": "inert",
        "authority": "none",
        "public": False,
    }
    envelope = {**body, "verification_digest": digest(body)}
    validation = validate_curator(
        "curator-verification-envelope-v1",
        envelope,
        enforce_canonical_envelope=False,
    )
    if not validation.valid:
        raise CuratorContractError(
            "generated Curator verification is invalid: " + "; ".join(validation.issues)
        )
    return deepcopy(envelope)


def curator_verification_bytes(request: Mapping[str, Any]) -> bytes:
    return canonical_bytes(compile_curator_verification(request))


def example_curator_request(*, known_budget: bool = True) -> dict[str, Any]:
    builder_request = example_builder_request(known_budget=known_budget)
    builder_envelope = compile_builder_implementation(builder_request)
    subject_commit = builder_request["scope"]["subject_commit"]
    subject_tree = builder_request["scope"]["subject_tree"]
    base_commit = "32f41bbb013464d1c3a98aab95f5bd75705b7ba2"
    base_tree = "0" * 40
    acceptance = [
        {
            "acceptance_id": "acceptance:curator-contracts",
            "statement": "Fourteen strict contracts and eleven separately sealed verification outputs validate deterministically.",
        },
        {
            "acceptance_id": "acceptance:hostile-verification",
            "statement": "False-green, self-verification, forged, stale, leaking, weakened, and substituted evidence fails closed.",
        },
        {
            "acceptance_id": "acceptance:authority-free",
            "statement": "The Curator remains inert, package-private, capability-free, tool-free, and unable to approve or release its own work.",
        },
    ]
    claims = [
        {
            "claim_id": "claim:strict-curator-contracts",
            "statement": "The candidate provides strict request-bound Curator verification contracts.",
            "claim_type": "implementation",
            "material": True,
            "acceptance_refs": ["acceptance:curator-contracts"],
            "builder_evidence_refs": ["evidence:source", "evidence:inventory"],
            "source_refs": ["source:constitution", "source:p08"],
        },
        {
            "claim_id": "claim:hostile-evidence-controls",
            "statement": "The candidate rejects false-green, self-verification, forged, stale, leaking, weakened, and substituted evidence.",
            "claim_type": "security",
            "material": True,
            "acceptance_refs": ["acceptance:hostile-verification"],
            "builder_evidence_refs": ["evidence:test-before", "evidence:test-after"],
            "source_refs": ["source:constitution", "source:p08"],
        },
        {
            "claim_id": "claim:authority-isolation",
            "statement": "The Curator candidate has no implementation, execution, completion, release, approval, promotion, or activation authority.",
            "claim_type": "release",
            "material": True,
            "acceptance_refs": ["acceptance:authority-free"],
            "builder_evidence_refs": ["evidence:inventory", "evidence:wheel"],
            "source_refs": ["source:constitution", "source:phase5-handoff"],
        },
    ]
    checks = [
        {
            "check_id": "check:strict-contract-catalog",
            "command": "python -m unittest tests.test_phase5d_curator_playbook.CuratorContractTests",
            "expected": "pass",
            "claim_refs": ["claim:strict-curator-contracts"],
            "acceptance_refs": ["acceptance:curator-contracts"],
            "sealed_before_candidate_access": True,
        },
        {
            "check_id": "check:hostile-evidence",
            "command": "python -m unittest tests.test_phase5d_curator_playbook.CuratorAdversarialTests",
            "expected": "pass",
            "claim_refs": ["claim:hostile-evidence-controls"],
            "acceptance_refs": ["acceptance:hostile-verification"],
            "sealed_before_candidate_access": True,
        },
        {
            "check_id": "check:authority-and-wheel",
            "command": "python scripts/verify_phase5d_installed_wheel.py --installed-root .wheel-install --output dist/phase5d-installed-wheel.json",
            "expected": "pass",
            "claim_refs": ["claim:authority-isolation"],
            "acceptance_refs": ["acceptance:authority-free"],
            "sealed_before_candidate_access": True,
        },
    ]
    receipt_fields = [
        "command",
        "exit_code",
        "started_at",
        "finished_at",
        "stdout_digest",
        "stderr_digest",
        "subject_commit",
        "subject_tree",
    ]
    evidence = [
        {
            "evidence_id": "evidence:source",
            "kind": "source",
            "digest": "sha256:" + ("1" * 64),
            "subject_commit": subject_commit,
            "subject_tree": subject_tree,
            "producer_role": "builder",
            "producer_actor_id": "procedural:builder",
            "integrity_status": "digest-verified",
            "stale": False,
            "claim_refs": ["claim:strict-curator-contracts"],
            "acceptance_refs": ["acceptance:curator-contracts"],
            "receipt_fields": receipt_fields,
        },
        {
            "evidence_id": "evidence:inventory",
            "kind": "inventory",
            "digest": "sha256:" + ("2" * 64),
            "subject_commit": subject_commit,
            "subject_tree": subject_tree,
            "producer_role": "integrator",
            "producer_actor_id": "procedural:integrator",
            "integrity_status": "digest-verified",
            "stale": False,
            "claim_refs": ["claim:strict-curator-contracts", "claim:authority-isolation"],
            "acceptance_refs": ["acceptance:curator-contracts", "acceptance:authority-free"],
            "receipt_fields": receipt_fields,
        },
        {
            "evidence_id": "evidence:test-before",
            "kind": "test-before",
            "digest": "sha256:" + ("3" * 64),
            "subject_commit": base_commit,
            "subject_tree": base_tree,
            "producer_role": "curator",
            "producer_actor_id": "procedural:curator",
            "integrity_status": "digest-verified",
            "stale": False,
            "claim_refs": ["claim:hostile-evidence-controls"],
            "acceptance_refs": ["acceptance:hostile-verification"],
            "receipt_fields": receipt_fields,
        },
        {
            "evidence_id": "evidence:test-after",
            "kind": "test-after",
            "digest": "sha256:" + ("4" * 64),
            "subject_commit": subject_commit,
            "subject_tree": subject_tree,
            "producer_role": "curator",
            "producer_actor_id": "procedural:curator",
            "integrity_status": "digest-verified",
            "stale": False,
            "claim_refs": ["claim:hostile-evidence-controls"],
            "acceptance_refs": ["acceptance:hostile-verification"],
            "receipt_fields": receipt_fields,
        },
        {
            "evidence_id": "evidence:wheel",
            "kind": "artifact",
            "digest": "sha256:" + ("5" * 64),
            "subject_commit": subject_commit,
            "subject_tree": subject_tree,
            "producer_role": "external-system",
            "producer_actor_id": "github-actions:build-evidence",
            "integrity_status": "digest-verified",
            "stale": False,
            "claim_refs": ["claim:authority-isolation"],
            "acceptance_refs": ["acceptance:authority-free"],
            "receipt_fields": receipt_fields,
        },
    ]
    sources = [
        {
            "source_id": "source:constitution",
            "uri": "repo:evidence/sources/SRC-023-classic-gpt-pack/raw/00_CONSTITUTION.md",
            "version": "pinned",
            "digest": "sha256:" + ("6" * 64),
            "license_status": "admitted",
            "completeness": "complete",
            "claim_refs": [item["claim_id"] for item in claims],
        },
        {
            "source_id": "source:p08",
            "uri": "repo:docs/plan/P08_CURATOR_INDEPENDENCE.md",
            "version": "adopted",
            "digest": "sha256:" + ("7" * 64),
            "license_status": "admitted",
            "completeness": "complete",
            "claim_refs": ["claim:strict-curator-contracts", "claim:hostile-evidence-controls"],
        },
        {
            "source_id": "source:phase5-handoff",
            "uri": "user-provided:phase5c-and-remaining-roadmap-handoff",
            "version": "2026-07-31",
            "digest": "sha256:" + ("8" * 64),
            "license_status": "admitted",
            "completeness": "complete",
            "claim_refs": ["claim:authority-isolation"],
        },
    ]
    regression_targets = [
        {
            "target_id": "regression:curator-tests",
            "path": "tests/test_phase5d_curator_playbook.py",
            "baseline_digest": "sha256:" + ("9" * 64),
            "candidate_digest": "sha256:" + ("a" * 64),
            "test_refs": ["check:strict-contract-catalog", "check:hostile-evidence"],
            "assertions_before": 0,
            "assertions_after": 40,
            "test_functions_before": 0,
            "test_functions_after": 20,
        },
        {
            "target_id": "regression:legacy-curator",
            "path": "src/hive_mind_os/curator.py",
            "baseline_digest": "sha256:" + ("b" * 64),
            "candidate_digest": "sha256:" + ("b" * 64),
            "test_refs": ["check:authority-and-wheel"],
            "assertions_before": 1,
            "assertions_after": 1,
            "test_functions_before": 1,
            "test_functions_after": 1,
        },
    ]
    budgets = (
        {
            "tokens": 120_000,
            "cost_microunits": 1_200_000,
            "elapsed_ms": 3_600_000,
            "tool_calls": 120,
        }
        if known_budget
        else {axis: None for axis in RESOURCE_AXES}
    )
    reserve = 100_000 if known_budget else None
    return {
        "record_type": "curator-verification-request",
        "schema_version": 1,
        "request_id": "request:phase5d-example",
        "objective_id": "objective:phase5d-example",
        "tenant_id": builder_envelope["tenant_id"],
        "repository_id": builder_envelope["repository_id"],
        "objective": "Add an inert, package-private Curator deep-playbook candidate.",
        "objective_state": "ready",
        "base_commit": base_commit,
        "base_tree": base_tree,
        "subject_commit": subject_commit,
        "subject_tree": subject_tree,
        "builder_envelope": builder_envelope,
        "builder_identity": {
            "role": "builder",
            "actor_id": "procedural:builder",
            "authenticated": False,
        },
        "curator_identity": {
            "role": "curator",
            "actor_id": "procedural:curator",
            "authenticated": False,
        },
        "blind_seal_sequence": 1,
        "candidate_access_sequence": 2,
        "acceptance_criteria": acceptance,
        "claims": claims,
        "sealed_checks": checks,
        "observed_evidence": evidence,
        "sources": sources,
        "regression_targets": regression_targets,
        "rollback_refs": [
            "rollback:remove-phase5d-files",
            "rollback:restore-ci-and-adr-index",
        ],
        "rollback_verification_test_refs": [
            "check:strict-contract-catalog",
            "check:authority-and-wheel",
        ],
        "point_in_time": {
            "knowledge_cutoff_commit": subject_commit,
            "target_commit": subject_commit,
            "future_commit_refs": [],
        },
        "budgets": budgets,
        "verification_reserve_ppm": reserve,
        "evidence_reserve_ppm": reserve,
        "rollback_reserve_ppm": reserve,
        "actors": [
            {"role": role, "actor_id": f"procedural:{role}", "authenticated": False}
            for role in COURT_ROLES
        ],
        "prior_fingerprints": [],
        "requested_release_recommendation": "defer",
        "caller_claims": {
            "builder_complete": False,
            "tests_passed": False,
            "release_ready": False,
            "independent_verification_complete": False,
        },
    }
