from __future__ import annotations

import json
import math
from copy import deepcopy
from importlib.resources import files
from typing import Any, Mapping

from hive_mind_os.roles import DEFAULT_LIFECYCLE

from .canonical import canonical_bytes, digest, reject_private_content, stable_id
from .contracts import validate_foundation
from .generation import (
    GENERATOR_VERSION,
    compile_generation_zero_candidates,
    digest_bytes,
    verify_generated_candidates,
)
from .orchestrator_playbook_contracts import (
    AGENT_ID,
    BASE_DEFINITION_ID,
    COURT_ROLES,
    DEFINITION_ID,
    EXPECTED_SUCCESSOR_DIGEST,
    MAX_HANDOFF_REFS,
    ORCHESTRATOR_SCHEMA_NAMES,
    ROLE_INSTRUCTIONS,
    WORK_ROLES,
    has_bounded_progress_cycle,
    load_orchestrator_schema,
    validate_orchestrator,
)

BASE_CANONICAL_FILE_DIGEST = (
    "sha256:c0658b7a28af19bfb2f202dae21a79fe0d09dcbae97be14879780c1ad6f4132d"
)
BASE_CONTENT_DIGEST = (
    "sha256:da0a8a87b76bd375d3c1477ea9b626fcc299068ab5d725a61b3c8092b54b861a"
)
BASE_PROJECTION_DIGEST = (
    "sha256:38a6d6f8da8cced427f1618190eb5dc78a2597481f8df4c56d80784bc8fbffc2"
)
BASE_PROMPT_DIGEST = (
    "sha256:09e7c8fb0e5eb0fbe2e0a2ca55840f56572372c7110eb407c9d3140c6c688f82"
)
BASE_GENERATED_MANIFEST_DIGEST = (
    "sha256:e652f81353af4d0abe41b656ff0a16d71368510b4b3efe985eed99976376659d"
)
BUILTIN_AGENT_DIGEST = (
    "sha256:30f5693f9f47579fbe10fca60461da6f06c089a5e2140f0a0e40f6504ab41f7b"
)
BUILTIN_PROMPT_DIGEST = (
    "sha256:21a22117132696f50c750bc38dd3c97c34d084f73e7ca72cd88e0b294a69f66f"
)
BUILTIN_SKILL_DIGEST = (
    "sha256:47d1b252ba14cbe23eb58723366e12f4dd8ea931523d18527d602ac250068743"
)
BUILTIN_SKILL_INSTRUCTION_DIGEST = (
    "sha256:b554dcdb21181ba2eb9d9e47ac7ed70edc382ef70289ab6c5e7a719dfbf21811"
)

MAX_WORK_ITEMS = 7
MAX_DEPENDENCIES = 21
MAX_EVIDENCE_REFS = 64
MAX_ROLLBACK_REFS = 32
MAX_ANCESTRY_DEPTH = 8
MAX_PROGRESS_FINGERPRINTS = 32
MAX_TEXT = 4000
MAX_NESTED_VALUES = 2048

_RESPONSIBILITIES = (
    "freeze-objective-and-acceptance",
    "decompose-work-with-evidence-and-rollback",
    "bind-lifecycle-dependencies",
    "propose-budgets-with-recovery-reserves",
    "schedule-court-without-merging-authority",
    "detect-stall-recursion-and-unknowns",
    "produce-fail-closed-handoff",
)
_TYPED_OUTPUTS = (
    "orchestrator-objective-decomposition-v1",
    "orchestrator-dependency-graph-v1",
    "orchestrator-budget-plan-v1",
    "orchestrator-court-schedule-v1",
    "orchestrator-recovery-plan-v1",
    "orchestrator-stop-decision-v1",
    "orchestrator-handoff-v1",
)
_STOP_CONDITIONS = (
    "blocked-objective",
    "recovery-required",
    "budget-exhausted-or-unknown",
    "evidence-unknown-or-unverified",
    "recursion-limit",
    "progress-stall-or-cycle",
    "independence-unverified",
)
_PROHIBITED_ACTIONS = (
    "execute-work",
    "invoke-provider-or-tool",
    "issue-capability-or-budget-lease",
    "merge-role-authority",
    "self-approve-or-self-promote",
    "claim-independent-actors-from-labels",
    "claim-completion-from-plan-generation",
    "activate-runtime-or-scheduler",
)


class OrchestratorContractError(ValueError):
    """A Phase 5A request or generated artifact failed closed."""


def _layer(
    position: int,
    layer_id: str,
    kind: str,
    version: str,
    source_digests: list[str],
) -> dict[str, Any]:
    body = {
        "position": position,
        "layer_id": layer_id,
        "kind": kind,
        "version": version,
        "source_digests": source_digests,
    }
    return {**body, "digest": digest(body)}


def _verify_packaged_phase2_bytes(generated: dict[str, bytes]) -> None:
    foundation = files("hive_mind_os.foundation")
    canonical = foundation.joinpath("canonical", "agents", "orchestrator.json").read_bytes()
    if digest_bytes(canonical) != BASE_CANONICAL_FILE_DIGEST:
        raise ValueError("packaged Phase 2 Orchestrator canonical bytes drifted")
    generated_root = foundation.joinpath("generated")
    observed = {
        "manifest.json": generated_root.joinpath("manifest.json").read_bytes(),
        **{
            path: generated_root.joinpath(*path.split("/")).read_bytes()
            for path in generated
            if path != "manifest.json"
        },
    }
    issues = verify_generated_candidates(observed, expected_paths=generated)
    if issues:
        raise ValueError("packaged Phase 2 generated bytes drifted: " + "; ".join(issues))
    if digest_bytes(observed["manifest.json"]) != BASE_GENERATED_MANIFEST_DIGEST:
        raise ValueError("packaged Phase 2 generated manifest bytes drifted")


def _read_builtin_json(path: tuple[str, ...], expected_digest: str) -> dict[str, Any]:
    raw = files("hive_mind_os").joinpath("builtin_packages", "hive-core", *path).read_bytes()
    if digest_bytes(raw) != expected_digest:
        raise ValueError(f"packaged {'/'.join(path)} bytes drifted")
    document = json.loads(raw)
    if type(document) is not dict:
        raise ValueError(f"packaged {'/'.join(path)} is not an object")
    return document


def _compile_unpinned_successor() -> dict[str, Any]:
    generated = compile_generation_zero_candidates()
    _verify_packaged_phase2_bytes(generated)
    orchestrator_bytes = generated["agents/orchestrator.json"]
    orchestrator = json.loads(orchestrator_bytes)
    if not validate_foundation("agent-definition-v2", orchestrator).valid:
        raise ValueError("Phase 2 Orchestrator projection is contract-invalid")
    if (
        orchestrator["definition_id"] != BASE_DEFINITION_ID
        or orchestrator["content_digest"] != BASE_CONTENT_DIGEST
        or orchestrator["generator_version"] != GENERATOR_VERSION
        or digest_bytes(orchestrator_bytes) != BASE_PROJECTION_DIGEST
    ):
        raise ValueError("Phase 2 Orchestrator identity or projection drifted")
    prompt_layers = orchestrator["prompt_layers"]
    if (
        len(prompt_layers) != 1
        or prompt_layers[0]["layer_id"] != "generation-zero:orchestrator"
        or prompt_layers[0]["version"] != "1"
        or prompt_layers[0]["digest"] != BASE_PROMPT_DIGEST
    ):
        raise ValueError("Generation Zero Orchestrator prompt binding drifted")

    builtin_agent = _read_builtin_json(("agents", "orchestrator.json"), BUILTIN_AGENT_DIGEST)
    _read_builtin_json(("prompts", "orchestrator.json"), BUILTIN_PROMPT_DIGEST)
    builtin_skill = _read_builtin_json(("skills", "orchestrator.json"), BUILTIN_SKILL_DIGEST)
    builtin_instruction = _read_builtin_json(
        ("skills", "instructions", "orchestrator.json"),
        BUILTIN_SKILL_INSTRUCTION_DIGEST,
    )
    if builtin_agent.get("role_binding") != "orchestrator":
        raise ValueError("built-in Orchestrator role binding drifted")
    if builtin_agent.get("skill_ids") != ["skill.orchestrator"]:
        raise ValueError("built-in Orchestrator skill binding drifted")
    if builtin_skill.get("component_id") != "skill.orchestrator":
        raise ValueError("built-in Orchestrator skill identity drifted")
    if builtin_instruction.get("skill_id") != "skill.orchestrator":
        raise ValueError("built-in Orchestrator skill instruction drifted")

    schema_digests = {
        name: digest(load_orchestrator_schema(name))
        for name in ORCHESTRATOR_SCHEMA_NAMES
    }
    playbook = {
        "responsibilities": list(_RESPONSIBILITIES),
        "role_instructions": [
            {"role": role, "instruction": ROLE_INSTRUCTIONS[role]}
            for role in WORK_ROLES
        ],
        "typed_outputs": list(_TYPED_OUTPUTS),
        "stop_conditions": list(_STOP_CONDITIONS),
        "prohibited_actions": list(_PROHIBITED_ACTIONS),
    }
    lifecycle = [role.value for role in DEFAULT_LIFECYCLE]
    if lifecycle != ["orchestrator", *WORK_ROLES]:
        raise ValueError("constitutional lifecycle order drifted")
    layers = [
        _layer(
            1,
            BASE_DEFINITION_ID,
            "base",
            "2-candidate",
            [BASE_CONTENT_DIGEST, BASE_PROJECTION_DIGEST],
        ),
        _layer(
            2,
            "generation-zero:orchestrator",
            "prompt",
            "1",
            [BASE_PROMPT_DIGEST, BUILTIN_PROMPT_DIGEST],
        ),
        _layer(3, "orchestrator:deep-playbook", "playbook", "1", [digest(playbook)]),
        _layer(
            4,
            "skill.orchestrator",
            "skills",
            "1",
            [BUILTIN_SKILL_DIGEST, BUILTIN_SKILL_INSTRUCTION_DIGEST],
        ),
        _layer(
            5,
            "orchestrator:plan-request",
            "input",
            "1",
            [schema_digests["orchestrator-plan-request-v1"]],
        ),
        _layer(
            6,
            "orchestrator:typed-outputs",
            "outputs",
            "1",
            [digest({key: schema_digests[key] for key in _TYPED_OUTPUTS})],
        ),
        _layer(
            7,
            "orchestrator:phase5a-governance",
            "governance",
            "1",
            [
                digest(
                    {
                        "sources": [
                            "phase1-canonical-contracts",
                            "phase5a-handoff",
                        ],
                        "court": "P5A-001",
                    }
                )
            ],
        ),
        _layer(8, "generation-zero:lifecycle", "lifecycle", "1", [digest({"stages": lifecycle})]),
    ]
    requested = list(orchestrator["requested_capabilities"])
    body = {
        "record_type": "orchestrator-agent-successor",
        "schema_version": 1,
        "agent_id": AGENT_ID,
        "definition_id": DEFINITION_ID,
        "role_id": "orchestrator",
        "version": "2-shadow-1",
        "status": "candidate",
        "lineage_relation": "extends-inert",
        "base_definition_ref": BASE_DEFINITION_ID,
        "rollback_ref": BASE_DEFINITION_ID,
        "layers": layers,
        "requested_capabilities": list(requested),
        "effective_capabilities": [],
        "unsupported_capabilities": list(requested),
        "tool_refs": [],
        "input_contract_refs": ["orchestrator-plan-request-v1"],
        "output_contract_refs": list(_TYPED_OUTPUTS),
        "workflow_refs": ["generation-zero:lifecycle", "phase5a:orchestrator-plan"],
        "budgets": {
            "max_work_items": MAX_WORK_ITEMS,
            "max_dependencies": MAX_DEPENDENCIES,
            "max_evidence_refs": MAX_EVIDENCE_REFS,
            "max_rollback_refs": MAX_ROLLBACK_REFS,
            "max_handoff_refs": MAX_HANDOFF_REFS,
            "max_ancestry_depth": MAX_ANCESTRY_DEPTH,
            "max_progress_fingerprints": MAX_PROGRESS_FINGERPRINTS,
            "max_text": MAX_TEXT,
            "max_nested_values": MAX_NESTED_VALUES,
        },
        "playbook": playbook,
        "governance": {
            "source_refs": [
                "phase1-canonical-contracts",
                "phase2-foundation-contract",
                "phase5a-orchestrator-source-register",
            ],
            "court_refs": ["P2-FOUNDATION-001", "P5A-001"],
            "dissent_ref": "evidence/phase5a/PHASE5A_DISSENT.md",
            "activation_prerequisites": [
                "authenticated-independent-actors",
                "held-out-behavioral-evaluation",
                "independent-curator",
                "independent-judge",
                "separate-activation-court",
            ],
        },
        "activation": "inert",
        "authority": "none",
        "public": False,
    }
    candidate = {**body, "content_digest": digest(body)}
    validation = validate_orchestrator(
        "orchestrator-agent-successor-v1",
        candidate,
        enforce_reviewed_successor=False,
    )
    if not validation.valid:
        raise ValueError(
            "Orchestrator successor failed its contract: "
            + "; ".join(validation.issues)
        )
    return candidate


def compile_orchestrator_successor() -> dict[str, Any]:
    candidate = _compile_unpinned_successor()
    if candidate["content_digest"] != EXPECTED_SUCCESSOR_DIGEST:
        raise ValueError("Orchestrator successor differs from its reviewed digest")
    return deepcopy(candidate)


def orchestrator_successor_bytes() -> bytes:
    return canonical_bytes(compile_orchestrator_successor())


def _strict_json_copy(
    value: Any,
    *,
    path: str = "$",
    depth: int = 0,
    counter: list[int] | None = None,
) -> Any:
    if counter is None:
        counter = [0]
    counter[0] += 1
    if counter[0] > MAX_NESTED_VALUES:
        raise OrchestratorContractError("request exceeds the bounded nested-value limit")
    if depth > 16:
        raise OrchestratorContractError("request exceeds the bounded nesting depth")
    if value is None or type(value) in {bool, int}:
        return value
    if type(value) is str:
        if len(value) > MAX_TEXT:
            raise OrchestratorContractError(f"{path} exceeds the bounded text limit")
        return value
    if type(value) is float:
        if not math.isfinite(value):
            raise OrchestratorContractError(f"{path} contains a non-finite number")
        return value
    if type(value) is list:
        return [
            _strict_json_copy(item, path=f"{path}[{index}]", depth=depth + 1, counter=counter)
            for index, item in enumerate(value)
        ]
    if type(value) is dict:
        copied: dict[str, Any] = {}
        for key, item in value.items():
            if type(key) is not str:
                raise OrchestratorContractError(f"{path} contains a non-string key")
            copied[key] = _strict_json_copy(
                item,
                path=f"{path}.{key}",
                depth=depth + 1,
                counter=counter,
            )
        return copied
    raise OrchestratorContractError(f"{path} contains unsupported type {type(value).__name__}")


def _validated_request(request: Mapping[str, Any]) -> dict[str, Any]:
    if type(request) is not dict:
        raise OrchestratorContractError("Orchestrator request must be an exact object")
    copied = _strict_json_copy(request)
    try:
        reject_private_content(copied)
    except ValueError as error:
        raise OrchestratorContractError(str(error)) from error
    validation = validate_orchestrator("orchestrator-plan-request-v1", copied)
    if not validation.valid:
        raise OrchestratorContractError(
            "invalid Orchestrator request: " + "; ".join(validation.issues)
        )
    return copied


def _with_output_digest(document: dict[str, Any]) -> dict[str, Any]:
    return {**document, "output_digest": digest(document)}


def _output_scope(request: Mapping[str, Any], request_digest: str) -> dict[str, Any]:
    return {
        "request_id": request["request_id"],
        "request_digest": request_digest,
        "objective_id": request["objective_id"],
        "tenant_id": request["tenant_id"],
        "repository_id": request["repository_id"],
    }


def _work_items(request: Mapping[str, Any], request_digest: str) -> list[dict[str, Any]]:
    result: list[dict[str, Any]] = []
    prior_ids: list[str] = []
    for role in WORK_ROLES:
        work_id = stable_id("phase5a-work", {"request_digest": request_digest, "role": role})
        result.append(
            {
                "work_item_id": work_id,
                "request_id": request["request_id"],
                "objective_id": request["objective_id"],
                "request_digest": request_digest,
                "tenant_id": request["tenant_id"],
                "repository_id": request["repository_id"],
                "objective": request["objective"],
                "constraints": list(request["constraints"]),
                "role": role,
                "instruction": ROLE_INSTRUCTIONS[role],
                "dependencies": list(prior_ids),
                "evidence_refs": list(request["evidence_refs"]),
                "rollback_refs": list(request["rollback_refs"]),
                "acceptance_criteria": list(request["acceptance_criteria"]),
            }
        )
        prior_ids.append(work_id)
    return result


def _dependency_graph(
    request: Mapping[str, Any],
    request_digest: str,
    work_items: list[dict[str, Any]],
) -> dict[str, Any]:
    nodes = [
        {"work_item_id": item["work_item_id"], "role": item["role"], "position": index + 1}
        for index, item in enumerate(work_items)
    ]
    edges = [
        {"from": source["work_item_id"], "to": target["work_item_id"]}
        for source in nodes
        for target in nodes
        if source["position"] < target["position"]
    ]
    return _with_output_digest(
        {
            "record_type": "orchestrator-dependency-graph",
            "schema_version": 1,
            **_output_scope(request, request_digest),
            "nodes": nodes,
            "edges": edges,
            "acyclic": True,
            "complete_predecessor_binding": True,
        }
    )


def _budget_plan(request: Mapping[str, Any], request_digest: str) -> dict[str, Any]:
    budgets = dict(request["budgets"])
    values = tuple(budgets.values())
    allocations: dict[str, int | None] = {role: None for role in WORK_ROLES}
    rollback_reserve = request["rollback_reserve_ppm"]
    verification_reserve = request["verification_reserve_ppm"]
    if all(value is None for value in values):
        status = "unknown"
    elif any(value == 0 for value in values):
        status = "exhausted"
    else:
        status = "proposed"
        available = 1_000_000 - rollback_reserve - verification_reserve
        quotient, remainder = divmod(available, len(WORK_ROLES))
        for index, role in enumerate(WORK_ROLES):
            allocations[role] = quotient + (1 if index < remainder else 0)
    return _with_output_digest(
        {
            "record_type": "orchestrator-budget-plan",
            "schema_version": 1,
            **_output_scope(request, request_digest),
            "accounting_status": status,
            "ceilings": budgets,
            "rollback_reserve_ppm": rollback_reserve,
            "verification_reserve_ppm": verification_reserve,
            "role_allocation_ppm": allocations,
            "lease_status": "not-issued",
            "completion_authorized": False,
        }
    )


def _independence_status(actors: list[dict[str, Any]]) -> str:
    observed = {(actor["role"], actor["actor_id"]) for actor in actors}
    roles = {role for role, _ in observed}
    actor_ids = {actor_id for _, actor_id in observed}
    if set(COURT_ROLES).issubset(roles) and len(actor_ids) >= len(COURT_ROLES):
        return "procedural-only"
    return "unknown"


def _court_schedule(
    request: Mapping[str, Any],
    request_digest: str,
    independence: str,
) -> dict[str, Any]:
    actors = {actor["role"]: actor["actor_id"] for actor in request["actors"]}
    stages = []
    prior: list[str] = []
    for position, role in enumerate(COURT_ROLES, start=1):
        actor_id = actors.get(role)
        stages.append(
            {
                "position": position,
                "role": role,
                "actor_id": actor_id,
                "actor_status": (
                    "procedural-unverified" if actor_id is not None else "unassigned"
                ),
                "required_before": list(prior),
                "status": "pending",
            }
        )
        prior.append(role)
    return _with_output_digest(
        {
            "record_type": "orchestrator-court-schedule",
            "schema_version": 1,
            **_output_scope(request, request_digest),
            "stages": stages,
            "independence_status": independence,
            "authenticated_distinct_actors": False,
            "completion_authorized": False,
        }
    )



def _stop_decision(
    request: Mapping[str, Any],
    request_digest: str,
    budget: Mapping[str, Any],
    independence: str,
) -> dict[str, Any]:
    progress_values = list(request["progress_fingerprints"])
    progress = (
        "unknown"
        if not progress_values
        else "stalled"
        if has_bounded_progress_cycle(progress_values)
        else "progressing"
    )
    recursion = "limit-reached" if request["recursion_depth"] >= MAX_ANCESTRY_DEPTH else "bounded"
    evidence_refs = set(request["evidence_refs"])
    # The request may carry caller-asserted verification labels for traceability, but
    # Phase 5A has no authenticated verifier.  Complete caller claims are therefore
    # represented explicitly as claimed-but-unverified rather than as verified facts.
    claimed_refs = set(request["verification_claim_refs"])
    evidence = (
        "unknown"
        if not evidence_refs
        else "claimed-unverified"
        if claimed_refs == evidence_refs
        else "claims-incomplete"
    )
    budget_status = {
        "proposed": "available",
        "unknown": "unknown",
        "exhausted": "exhausted",
    }[budget["accounting_status"]]
    reasons: list[str] = []
    if progress == "unknown":
        reasons.append("progress-evidence-unknown")
    if budget_status == "unknown":
        reasons.append("budget-accounting-unknown")
    elif budget_status == "exhausted":
        reasons.append("budget-exhausted")
    if evidence == "claimed-unverified":
        reasons.append("evidence-verification-unavailable")
    elif evidence == "claims-incomplete":
        reasons.append("evidence-claims-incomplete")
    else:
        reasons.append("evidence-unknown")
    if independence != "procedural-only":
        reasons.append("required-role-labels-incomplete")
    reasons.append("authenticated-independence-unavailable")

    if request["objective_state"] == "recovering":
        decision = "recover"
        reasons.insert(0, "objective-recovery-required")
    elif request["objective_state"] == "blocked":
        decision = "stop"
        reasons.insert(0, "objective-blocked")
    elif recursion == "limit-reached":
        decision = "stop"
        reasons.insert(0, "recursion-limit-reached")
    elif progress == "stalled":
        decision = "stop"
        reasons.insert(0, "progress-loop-or-stall")
    elif budget_status == "exhausted":
        decision = "stop"
    else:
        decision = "defer"
    return _with_output_digest(
        {
            "record_type": "orchestrator-stop-decision",
            "schema_version": 1,
            **_output_scope(request, request_digest),
            "objective_state": request["objective_state"],
            "decision": decision,
            "reasons": reasons,
            "progress_status": progress,
            "budget_status": budget_status,
            "recursion_status": recursion,
            "evidence_status": evidence,
            "completion_authorized": False,
        }
    )


def _handoff(
    request: Mapping[str, Any],
    request_digest: str,
    stop: Mapping[str, Any],
    independence: str,
) -> dict[str, Any]:
    reasons = set(stop["reasons"])
    if (
        stop["decision"] in {"stop", "recover"}
        or stop["progress_status"] == "stalled"
        or stop["recursion_status"] == "limit-reached"
    ):
        next_role, reason = "steward", "recovery-or-stop-review"
    elif stop["evidence_status"] in {"unknown", "claims-incomplete"}:
        next_role, reason = "explorer", "evidence-gap-review"
    elif stop["budget_status"] != "available":
        next_role, reason = "steward", "budget-boundary-review"
    elif stop["evidence_status"] == "claimed-unverified" or independence in {
        "procedural-only",
        "unknown",
    }:
        next_role, reason = "curator", "independence-and-evidence-review"
    else:
        next_role, reason = "explorer", "next-lifecycle-stage"
    requested = request["requested_next_role"]
    required_refs = sorted(set(request["evidence_refs"]) | set(request["rollback_refs"]) | reasons)
    return _with_output_digest(
        {
            "record_type": "orchestrator-handoff",
            "schema_version": 1,
            **_output_scope(request, request_digest),
            "next_role": next_role,
            "requested_next_role": requested,
            "requested_role_eligible": requested == next_role,
            "reason": reason,
            "required_refs": required_refs,
            "activation_authorized": False,
        }
    )


def compile_orchestrator_plan(request: Mapping[str, Any]) -> dict[str, Any]:
    copied = _validated_request(request)
    successor = compile_orchestrator_successor()
    request_digest = digest(copied)
    work_items = _work_items(copied, request_digest)
    independence = _independence_status(copied["actors"])
    budget = _budget_plan(copied, request_digest)
    stop = _stop_decision(copied, request_digest, budget, independence)
    decomposition = _with_output_digest(
        {
            "record_type": "orchestrator-objective-decomposition",
            "schema_version": 1,
            **_output_scope(copied, request_digest),
            "objective": copied["objective"],
            "constraints": list(copied["constraints"]),
            "status": (
                "blocked"
                if stop["decision"] == "stop"
                else "deferred"
                if stop["decision"] in {"defer", "recover"}
                else "decomposed"
            ),
            "work_items": work_items,
            "unknowns": [
                reason
                for reason in stop["reasons"]
                if "unknown" in reason
                or "unavailable" in reason
                or "not-fully" in reason
                or "incomplete" in reason
            ],
            "completion_authorized": False,
        }
    )
    outputs = {
        "objective_decomposition": decomposition,
        "dependency_graph": _dependency_graph(copied, request_digest, work_items),
        "budget_plan": budget,
        "court_schedule": _court_schedule(copied, request_digest, independence),
        "recovery_plan": _with_output_digest(
            {
                "record_type": "orchestrator-recovery-plan",
                "schema_version": 1,
                **_output_scope(copied, request_digest),
                "rollback_refs": list(copied["rollback_refs"]),
                "checkpoint_required": True,
                "preserve_evidence": True,
                "resume_authority": "external-required",
                "activation_authorized": False,
            }
        ),
        "stop_decision": stop,
        "handoff": _handoff(copied, request_digest, stop, independence),
    }
    body = {
        "record_type": "orchestrator-plan-envelope",
        "schema_version": 1,
        "request_id": copied["request_id"],
        "objective_id": copied["objective_id"],
        "tenant_id": copied["tenant_id"],
        "repository_id": copied["repository_id"],
        "successor_digest": successor["content_digest"],
        "request_digest": request_digest,
        "request_snapshot": deepcopy(copied),
        "outputs": outputs,
        "activation": "inert",
        "authority": "none",
        "public": False,
    }
    envelope = {**body, "plan_digest": digest(body)}
    validation = validate_orchestrator("orchestrator-plan-envelope-v1", envelope)
    if not validation.valid:
        raise OrchestratorContractError(
            "generated Orchestrator plan is invalid: "
            + "; ".join(validation.issues)
        )
    return deepcopy(envelope)


def orchestrator_plan_bytes(request: Mapping[str, Any]) -> bytes:
    return canonical_bytes(compile_orchestrator_plan(request))


def example_orchestrator_request(*, known_budget: bool = True) -> dict[str, Any]:
    budgets = {
        "tokens": 100_000,
        "cost_microunits": 5_000_000,
        "elapsed_ms": 3_600_000,
        "tool_calls": 100,
    } if known_budget else {
        "tokens": None,
        "cost_microunits": None,
        "elapsed_ms": None,
        "tool_calls": None,
    }
    actors = [
        {"role": role, "actor_id": f"procedural:{role}", "authenticated": False}
        for role in COURT_ROLES
    ]
    return {
        "record_type": "orchestrator-plan-request",
        "schema_version": 1,
        "request_id": "request:phase5a-example",
        "objective_id": "objective:phase5a-example",
        "tenant_id": "tenant:local",
        "repository_id": "repository:hive-mind-os",
        "objective": "Produce a bounded, evidence-dependent plan without executing or expanding authority.",
        "acceptance_criteria": ["all typed outputs validate", "no execution authority is created"],
        "constraints": ["remain inert", "preserve rollback"],
        "evidence_refs": ["evidence:phase5a-handoff"],
        "verification_claim_refs": ["evidence:phase5a-handoff"],
        "rollback_refs": [BASE_DEFINITION_ID],
        "budgets": budgets,
        "rollback_reserve_ppm": 100_000 if known_budget else None,
        "verification_reserve_ppm": 150_000 if known_budget else None,
        "actors": actors,
        "ancestry": [],
        "recursion_depth": 0,
        "progress_fingerprints": ["progress:objective-frozen", "progress:dependencies-bound"],
        "objective_state": "proposed",
        "requested_next_role": "explorer",
    }
