"""Hive Mind OS agent kernel."""

from .autonomy import (
    AgentVariant,
    AutonomousMissionLoop,
    AutonomyBudget,
    EvolutionArena,
    MissionCharter,
)
from .classic_gpt import (
    ActionKind,
    ClassicGptSimulationGate,
    ClassicGptSourcePack,
    ClassicGptTurn,
    SimulatedAction,
    SimulationPhase,
)
from .contracts import (
    ContractValidation,
    load_schema,
    validate_contract,
    validate_runtime_state,
    validate_schema_catalog,
)
from .courtroom import (
    BurdenOfProof,
    CourtCase,
    Courtroom,
    CourtVerdict,
    Disposition,
    SourceDocketAuditor,
    SourceRecord,
)
from .current_state_audit import (
    AUDITED_BASELINE,
    AuditVerificationContext,
    build_audit_verification_context,
    collect_current_state_audit,
    create_audit_artifact,
    verify_audit_artifact,
    write_audit_artifact,
)
from .durable_model_execution import (
    DurableModelExecutionContext,
    DurableModelExecutionError,
    DurableModelRoleExecutor,
)
from .experiment_runner import (
    ExperimentRun,
    ExperimentRunner,
    FixtureMissionSurface,
    PITEpisodeSurface,
)
from .github_adapter import (
    CheckResult,
    GitHubClient,
    GitHubDelivery,
    GitHubDeliveryTarget,
    ProtectionReport,
    PullRequestResult,
    PushResult,
)
from .governed_sources import GovernedSourceAudit, audit_governed_source
from .ingestion import (
    AdjudicationRecord,
    DeferredObligation,
    ExhibitStore,
    LicenseRecord,
    SourceExhibit,
    adjudicate_with_exhibit,
    defer_obligation,
    register_exhibit,
)
from .mission import MissionReport, RepositoryMission, ScriptedRepositoryBackend
from .mission_store import (
    MissionStore,
    ReconciliationError,
    StepCheckpoint,
    resume_mission,
)
from .models import AutonomyLevel, Objective, RiskTier, Role
from .package_system import (
    AgentManifest,
    CatalogSnapshot,
    ComponentKind,
    ComponentRef,
    ConformanceStatus,
    EvidenceLevel,
    FileRecord,
    HostCapability,
    HostCapabilityProfile,
    LicenseStatus,
    LoadedPackage,
    OODAContractValidation,
    OODAPhase,
    OODAState,
    OODAStatus,
    OODATerminalRecord,
    OODATransition,
    PackageCatalog,
    PackageManifest,
    PackagePin,
    PackageValidationError,
    SkillManifest,
    ToolManifest,
    TrustState,
    WorkflowManifest,
    WorkflowTransition,
    load_builtin_host_profile,
    load_builtin_host_profiles,
    validate_ooda_contract,
)
from .projection import (
    DEFAULT_PROJECTION_SCHEMA_VERSION,
    WAR_ROOM_PROJECTION_SCHEMA_VERSION,
    build_projection,
    build_war_room_projection,
    projection_html,
    projection_json,
)
from .prompt_registry import PromptRegistry, generation_zero_prompt, prompt_digest
from .receipts import (
    FileReceiptValidator,
    ReceiptReference,
    ReceiptResult,
    ReceiptValidation,
    ReceiptValidator,
    sha256_digest,
)
from .recursive_improvement import (
    ExperimentCandidate,
    ExperimentDecision,
    ExperimentEvidence,
    ExperimentVerdict,
    MetricDirection,
    MetricObservation,
    MetricSpec,
    RecursiveImprovementContract,
    RecursiveImprovementController,
    RecursiveImprovementGate,
)
from .repository_learning import RepositoryLearningCurriculum, RepositoryScout
from .runtime import HiveKernel
from .scheduler import Job, ManualClock, Scheduler, StaleLeaseError, SystemClock
from .source_docket import (
    FoundingSourceDocket,
    load_default_source_docket,
    load_source_docket,
)
from .vision import HardenedVisionContract, VisionComplianceGate
from .workers import Worker, serve

__all__ = [
    "ActionKind",
    "AgentManifest",
    "AgentVariant",
    "AutonomyBudget",
    "AutonomyLevel",
    "AutonomousMissionLoop",
    "AUDITED_BASELINE",
    "AuditVerificationContext",
    "AdjudicationRecord",
    "BurdenOfProof",
    "ClassicGptSimulationGate",
    "ClassicGptSourcePack",
    "ClassicGptTurn",
    "CatalogSnapshot",
    "ComponentKind",
    "ComponentRef",
    "ConformanceStatus",
    "ContractValidation",
    "CourtCase",
    "Courtroom",
    "CourtVerdict",
    "Disposition",
    "DeferredObligation",
    "DEFAULT_PROJECTION_SCHEMA_VERSION",
    "DurableModelExecutionContext",
    "DurableModelExecutionError",
    "DurableModelRoleExecutor",
    "EvolutionArena",
    "EvidenceLevel",
    "ExhibitStore",
    "ExperimentCandidate",
    "ExperimentDecision",
    "ExperimentEvidence",
    "ExperimentVerdict",
    "ExperimentRun",
    "ExperimentRunner",
    "FoundingSourceDocket",
    "FileRecord",
    "FileReceiptValidator",
    "FixtureMissionSurface",
    "HardenedVisionContract",
    "HiveKernel",
    "HostCapability",
    "HostCapabilityProfile",
    "Job",
    "GovernedSourceAudit",
    "GitHubClient",
    "GitHubDelivery",
    "GitHubDeliveryTarget",
    "LicenseRecord",
    "LicenseStatus",
    "LoadedPackage",
    "ManualClock",
    "MetricDirection",
    "MetricObservation",
    "MetricSpec",
    "MissionCharter",
    "MissionReport",
    "MissionStore",
    "Objective",
    "OODAContractValidation",
    "OODAPhase",
    "OODAState",
    "OODAStatus",
    "OODATerminalRecord",
    "OODATransition",
    "PITEpisodeSurface",
    "ProtectionReport",
    "PackageCatalog",
    "PackageManifest",
    "PackagePin",
    "PackageValidationError",
    "PullRequestResult",
    "PromptRegistry",
    "PushResult",
    "RecursiveImprovementContract",
    "RecursiveImprovementController",
    "RecursiveImprovementGate",
    "RepositoryLearningCurriculum",
    "RepositoryMission",
    "ReconciliationError",
    "RepositoryScout",
    "ReceiptReference",
    "ReceiptResult",
    "ReceiptValidator",
    "ReceiptValidation",
    "RiskTier",
    "Role",
    "Scheduler",
    "SimulatedAction",
    "SimulationPhase",
    "SkillManifest",
    "ScriptedRepositoryBackend",
    "SourceDocketAuditor",
    "SourceExhibit",
    "SourceRecord",
    "StepCheckpoint",
    "StaleLeaseError",
    "SystemClock",
    "ToolManifest",
    "TrustState",
    "CheckResult",
    "VisionComplianceGate",
    "Worker",
    "WAR_ROOM_PROJECTION_SCHEMA_VERSION",
    "WorkflowManifest",
    "WorkflowTransition",
    "audit_governed_source",
    "adjudicate_with_exhibit",
    "build_audit_verification_context",
    "build_projection",
    "build_war_room_projection",
    "collect_current_state_audit",
    "create_audit_artifact",
    "defer_obligation",
    "generation_zero_prompt",
    "load_default_source_docket",
    "load_schema",
    "load_builtin_host_profile",
    "load_builtin_host_profiles",
    "load_source_docket",
    "register_exhibit",
    "prompt_digest",
    "projection_html",
    "projection_json",
    "resume_mission",
    "sha256_digest",
    "serve",
    "validate_contract",
    "validate_ooda_contract",
    "validate_runtime_state",
    "validate_schema_catalog",
    "verify_audit_artifact",
    "write_audit_artifact",
]
__version__ = "0.6.0"
