from __future__ import annotations

from .courtroom import BurdenOfProof, Disposition, ImplementationState, SourceRecord, SourceStatus
from .founding_docket import ClaimSpec


ADDITIONAL_SOURCES: tuple[SourceRecord, ...] = (
    SourceRecord(
        id="SRC-016",
        title="Auto Claude autonomous coding framework video",
        uri="https://www.youtube.com/watch?v=eaNA2oOXoUg",
        kind="video",
        status=SourceStatus.PARTIAL,
        version_ref="youtube:eaNA2oOXoUg",
        license_spdx=None,
        content_digest=None,
    ),
    SourceRecord(
        id="SRC-017",
        title="User-supplied reference video IbFaY3xFpZM",
        uri="https://www.youtube.com/watch?v=IbFaY3xFpZM",
        kind="video",
        status=SourceStatus.PENDING_INGESTION,
        version_ref="youtube:IbFaY3xFpZM",
        license_spdx=None,
        content_digest=None,
    ),
    SourceRecord(
        id="SRC-018",
        title="Building AI Agents that actually work full course",
        uri="https://www.youtube.com/watch?v=eA9Zf2-qYYM",
        kind="video",
        status=SourceStatus.PARTIAL,
        version_ref="youtube:eA9Zf2-qYYM",
        license_spdx=None,
        content_digest=None,
    ),
    SourceRecord(
        id="SRC-019",
        title="OpenClaw and OpenCode autonomous engineering team video",
        uri="https://www.youtube.com/watch?v=kIWMLL0S8X8",
        kind="video",
        status=SourceStatus.PARTIAL,
        version_ref="youtube:kIWMLL0S8X8",
        license_spdx=None,
        content_digest=None,
    ),
)


ADDITIONAL_CLAIMS: tuple[ClaimSpec, ...] = (
    ClaimSpec(
        "CLM-058",
        ("SRC-016",),
        "Long-running autonomous coding should use specification-driven decomposition, bounded parallel subagents, validation loops, and objective completion criteria",
        "autonomous_coding",
        disposition=Disposition.ADAPT,
        section="role-and-workflow-plane",
        rationale="Adapt the long-running coding mechanism while requiring bounded leases, traceable task graphs, independent validation, and explicit stop conditions.",
    ),
    ClaimSpec(
        "CLM-059",
        ("SRC-016",),
        "Mission control should expose plans, subagent work, progress, code and validation state, stalls, budgets, and security findings, with findings convertible into traceable tasks",
        "experience",
        disposition=Disposition.ADAPT,
        section="experience-plane",
        rationale="Adopt operational visibility as a projection of the evidence ledger rather than a decorative or self-reported status board.",
    ),
    ClaimSpec(
        "CLM-060",
        ("SRC-017",),
        "Every atomic idea in the IbFaY3xFpZM video must be transcript-ingested, time-coded, cross-examined, and mapped before promotion",
        "source_ingestion",
        disposition=Disposition.DEFER,
        burden=BurdenOfProof.CAPTURE,
        state=ImplementationState.INVENTORIED,
        rationale="Preserve the user-supplied source as a blocking evidence obligation and prohibit invented content until a verified transcript or artifact is available.",
    ),
    ClaimSpec(
        "CLM-061",
        ("SRC-018",),
        "Agent execution should be a goal-to-result observe-think-act loop with explicit success, retry, escalation, and stop conditions rather than a one-turn chat response",
        "agent_loop",
        disposition=Disposition.ADAPT,
        section="role-and-workflow-plane",
        rationale="Adopt iterative goal execution behind durable state, bounded authority, objective evidence, and deterministic stopping rules.",
    ),
    ClaimSpec(
        "CLM-062",
        ("SRC-018",),
        "Agent instructions, project context, and cross-session memory should be versioned, scoped, portable, inspectable, correction-aware, and unable to silently mutate the constitution",
        "context_and_memory",
        disposition=Disposition.ADAPT,
        section="knowledge-skill-and-workflow-plane",
        rationale="Adapt persistent context and memory while preserving provenance, freshness, correction history, explicit forgetting, and constitutional precedence.",
    ),
    ClaimSpec(
        "CLM-063",
        ("SRC-018",),
        "Reusable skills and scheduled automations should compound capability only when versioned, tested, permission-scoped, observable, and promotion-gated",
        "skills_and_automation",
        disposition=Disposition.ADAPT,
        section="knowledge-skill-and-workflow-plane",
        rationale="Treat skills as governed executable SOPs and schedules as durable triggers, not as unreviewed prompt accumulation.",
    ),
    ClaimSpec(
        "CLM-064",
        ("SRC-018",),
        "External tools connected through MCP-style adapters must inherit agent identity, authority, budgets, provenance, idempotency, and rollback obligations",
        "tool_integration",
        disposition=Disposition.ADAPT,
        section="integration-plane",
        rationale="Adopt broad tool connectivity without allowing a connector to broaden the caller's authority or bypass the evidence chain.",
    ),
    ClaimSpec(
        "CLM-065",
        ("SRC-019",),
        "Persistent orchestration and coding execution should be separable so a durable automation hub can dispatch work to replaceable coding engines, models, and sandboxes",
        "orchestration",
        disposition=Disposition.ADAPT,
        section="control-plane",
        rationale="Separate control-plane durability from execution backends so either can evolve, fail, or be replaced without rewriting role semantics.",
    ),
    ClaimSpec(
        "CLM-066",
        ("SRC-019",),
        "Messaging and remote-control channels may trigger and inspect workflows but must not bypass typed objectives, policy checks, secret handling, sandboxing, budgets, or evidence gates",
        "channel_security",
        disposition=Disposition.ADAPT,
        section="integration-plane",
        rationale="Adapt channel-driven automation while keeping all authority and side effects inside the kernel's governed execution path.",
    ),
)
