from __future__ import annotations

from .courtroom import BurdenOfProof, Disposition, ImplementationState, SourceRecord, SourceStatus
from .founding_docket import ClaimSpec


CLASSIC_GPT_SOURCES: tuple[SourceRecord, ...] = (
    SourceRecord(
        id="SRC-022",
        title="Classic GPT Hive Mind OS simulation hardening instruction",
        uri="user-supplied:classic-gpt-simulation-instruction",
        kind="user_requirement",
        status=SourceStatus.VERIFIED,
        version_ref="conversation:2026-07-27",
        license_spdx=None,
        content_digest="classic-gpt-simulation-v1",
    ),
)


CLASSIC_GPT_CLAIMS: tuple[ClaimSpec, ...] = (
    ClaimSpec(
        "CLM-074",
        ("SRC-022",),
        "A classic GPT may simulate Hive Mind OS reasoning but must never represent simulated autonomy, memory, tool use, or side effects as real execution without external receipts",
        "simulation_truthfulness",
        disposition=Disposition.ADAPT,
        burden=BurdenOfProof.IMPLEMENT,
        state=ImplementationState.IMPLEMENTED,
        section="constitutional-and-court-governance",
        code_refs=(
            "src/hive_mind_os/classic_gpt.py",
            "src/hive_mind_os/receipts.py",
            "gpt_sources/00_HIVE_MIND_SYSTEM_INSTRUCTIONS.md",
        ),
        test_refs=("tests/test_classic_gpt.py", "tests/test_receipts.py"),
        metrics=("false_execution_claim_rate=0", "unreceipted_side_effect_rate=0"),
        rationale="Permit a high-fidelity reasoning simulation while making the boundary between model output and externally executed work explicit and machine-checkable.",
    ),
    ClaimSpec(
        "CLM-075",
        ("SRC-022",),
        "Classic GPT simulation must externalize a complete portable mission state instead of relying on hidden chat memory",
        "portable_state",
        disposition=Disposition.ADAPT,
        burden=BurdenOfProof.IMPLEMENT,
        state=ImplementationState.IMPLEMENTED,
        section="evidence-and-memory-plane",
        code_refs=("src/hive_mind_os/classic_gpt.py", "gpt_sources/01_RUNTIME_STATE_SCHEMA.json"),
        test_refs=("tests/test_classic_gpt.py",),
        metrics=("resume_without_restatement_rate", "state_schema_validity_rate"),
        rationale="Treat chat context as a cache; authoritative state lives in an inspectable, versioned mission packet.",
    ),
    ClaimSpec(
        "CLM-076",
        ("SRC-022",),
        "All eight specialist roles and courtroom participants must run as labeled passes with explicit identity separation and conflict-of-interest checks",
        "role_simulation",
        disposition=Disposition.ADAPT,
        burden=BurdenOfProof.IMPLEMENT,
        state=ImplementationState.IMPLEMENTED,
        section="role-and-workflow-plane",
        code_refs=("src/hive_mind_os/classic_gpt.py", "gpt_sources/02_ROLE_AND_COURT_PROTOCOL.md"),
        test_refs=("tests/test_classic_gpt.py",),
        metrics=("role_coverage_rate", "self_verification_rate=0"),
        rationale="A single model may emulate multiple responsibilities only when each pass is separately identified and no acting pass is accepted as independent verification.",
    ),
    ClaimSpec(
        "CLM-077",
        ("SRC-022",),
        "Every simulated side effect must remain a proposal until a matching external tool receipt is supplied and bound to the mission state",
        "tool_receipts",
        disposition=Disposition.ADAPT,
        burden=BurdenOfProof.IMPLEMENT,
        state=ImplementationState.IMPLEMENTED,
        section="execution-plane",
        code_refs=(
            "src/hive_mind_os/classic_gpt.py",
            "src/hive_mind_os/receipts.py",
            "gpt_sources/03_TOOL_EVIDENCE_AND_HANDOFF_PROTOCOL.md",
        ),
        test_refs=("tests/test_classic_gpt.py", "tests/test_receipts.py"),
        metrics=("proposal_to_receipt_traceability", "fabricated_completion_rate=0"),
        rationale="Prevent a text-only model from converting intention, generated code, or a suggested command into a false claim that work was executed.",
    ),
    ClaimSpec(
        "CLM-078",
        ("SRC-022",),
        "Classic GPT simulation must use progressive source loading, explicit precedence, and context compaction without silently dropping unresolved evidence, dissent, blockers, or rollback data",
        "context_management",
        disposition=Disposition.ADAPT,
        burden=BurdenOfProof.IMPLEMENT,
        state=ImplementationState.IMPLEMENTED,
        section="knowledge-skill-and-workflow-plane",
        code_refs=("src/hive_mind_os/classic_gpt.py", "gpt_sources/manifest.json"),
        test_refs=("tests/test_classic_gpt.py",),
        metrics=("source_pack_completeness", "silent_context_omission_rate=0"),
        rationale="Make token limits explicit and preserve constitutional, evidentiary, and recovery-critical state during compaction.",
    ),
    ClaimSpec(
        "CLM-079",
        ("SRC-022",),
        "A simulated mission may be marked complete only after all role passes, independent verification, evidence references, resolved blockers, and receipted side effects are present",
        "completion_gate",
        disposition=Disposition.ADAPT,
        burden=BurdenOfProof.IMPLEMENT,
        state=ImplementationState.IMPLEMENTED,
        section="assurance-and-benchmark-plane",
        code_refs=("src/hive_mind_os/classic_gpt.py", "src/hive_mind_os/receipts.py"),
        test_refs=("tests/test_classic_gpt.py", "tests/test_receipts.py"),
        metrics=("false_completion_rate=0", "completion_evidence_coverage"),
        rationale="Replace conversational confidence with a fail-closed completion contract.",
    ),
    ClaimSpec(
        "CLM-080",
        ("SRC-022",),
        "Every classic GPT turn must emit a resumable next-action and state reference so another session or model can continue without reconstructing hidden reasoning",
        "handoff",
        disposition=Disposition.ADAPT,
        burden=BurdenOfProof.IMPLEMENT,
        state=ImplementationState.IMPLEMENTED,
        section="control-plane",
        code_refs=("src/hive_mind_os/classic_gpt.py", "gpt_sources/03_TOOL_EVIDENCE_AND_HANDOFF_PROTOCOL.md"),
        test_refs=("tests/test_classic_gpt.py",),
        metrics=("handoff_completeness", "cross_session_resume_success_rate"),
        rationale="Make continuation artifact-based and model-portable rather than dependent on one conversation window.",
    ),
)
