from __future__ import annotations

from .courtroom import BurdenOfProof, Disposition, ImplementationState, SourceRecord, SourceStatus
from .founding_docket import ClaimSpec


RECURSIVE_IMPROVEMENT_SOURCES: tuple[SourceRecord, ...] = (
    SourceRecord(
        id="SRC-020",
        title="Recursive Self Improvement — Emergent Garden",
        uri="https://www.youtube.com/watch?v=t7_ZXgfJVG8",
        kind="video",
        status=SourceStatus.PARTIAL,
        version_ref="youtube:t7_ZXgfJVG8",
        license_spdx=None,
        content_digest=None,
    ),
    SourceRecord(
        id="SRC-021",
        title="Karpathy AutoResearch autonomous experiment loop",
        uri="https://github.com/karpathy/autoresearch",
        kind="repository",
        status=SourceStatus.VERIFIED,
        version_ref="228791fb499afffb54b46200aca536f79142f117",
        license_spdx="MIT",
        content_digest=None,
    ),
)


RECURSIVE_IMPROVEMENT_CLAIMS: tuple[ClaimSpec, ...] = (
    ClaimSpec(
        "CLM-067",
        ("SRC-020", "SRC-021"),
        "Weak recursive improvement should optimize bounded external code, strategies, prompts, workflows, and configurations as versioned challengers rather than mutating the live champion, mission, policy, or model weights",
        "recursive_improvement_scope",
        disposition=Disposition.ADAPT,
        burden=BurdenOfProof.IMPLEMENT,
        state=ImplementationState.IMPLEMENTED,
        section="learning-and-evolution-plane",
        code_refs=("src/hive_mind_os/recursive_improvement.py",),
        test_refs=("tests/test_recursive_improvement.py",),
        metrics=("eligible_challenger_rate", "live_champion_mutation_rate=0"),
        rationale="Adopt bounded weak RSI while rejecting in-place champion mutation, self-weight modification, goal drift, and authority expansion.",
    ),
    ClaimSpec(
        "CLM-068",
        ("SRC-020", "SRC-021"),
        "Every recursive-improvement episode must follow propose, isolate, implement, test, independently evaluate, keep or discard, record, and repeat with complete retained artifacts",
        "experiment_loop",
        disposition=Disposition.ADAPT,
        burden=BurdenOfProof.IMPLEMENT,
        state=ImplementationState.IMPLEMENTED,
        section="learning-and-evolution-plane",
        code_refs=("src/hive_mind_os/recursive_improvement.py",),
        test_refs=("tests/test_recursive_improvement.py",),
        metrics=("experiment_artifact_completeness", "reproducible_decision_rate"),
        rationale="Turn autonomous trial and error into a typed, reversible, independently judged state machine instead of an opaque self-modifying loop.",
    ),
    ClaimSpec(
        "CLM-069",
        ("SRC-020", "SRC-021"),
        "Candidate promotion must require repeated measurements that exceed the measured noise floor under a pinned evaluation contract",
        "statistical_evaluation",
        disposition=Disposition.ADAPT,
        burden=BurdenOfProof.IMPLEMENT,
        state=ImplementationState.IMPLEMENTED,
        section="assurance-and-benchmark-plane",
        code_refs=("src/hive_mind_os/recursive_improvement.py",),
        test_refs=("tests/test_recursive_improvement.py",),
        metrics=("false_promotion_rate", "retest_rate", "effect_over_noise"),
        rationale="Adapt fixed-budget empirical comparison while preventing tiny noisy changes from being promoted as real progress.",
    ),
    ClaimSpec(
        "CLM-070",
        ("SRC-020",),
        "Metric gaming, protected-holdout access, self-evaluation, missing artifacts, and policy violations must quarantine a candidate even when its headline metric improves",
        "anti_reward_hacking",
        disposition=Disposition.ADAPT,
        burden=BurdenOfProof.IMPLEMENT,
        state=ImplementationState.IMPLEMENTED,
        section="constitutional-and-court-governance",
        code_refs=("src/hive_mind_os/recursive_improvement.py",),
        test_refs=("tests/test_recursive_improvement.py",),
        metrics=("metric_gaming_escape_rate=0", "holdout_leakage_rate=0", "self_evaluation_rate=0"),
        rationale="Treat reward hacking and leakage as disqualifying evidence, not as small score penalties that can be outweighed by performance.",
    ),
    ClaimSpec(
        "CLM-071",
        ("SRC-020", "SRC-021"),
        "Recursive improvement must optimize a primary metric only inside hard quality, trust, security, latency, cost, and resource guardrails",
        "multi_objective_fitness",
        disposition=Disposition.ADAPT,
        burden=BurdenOfProof.IMPLEMENT,
        state=ImplementationState.IMPLEMENTED,
        section="learning-and-evolution-plane",
        code_refs=("src/hive_mind_os/recursive_improvement.py",),
        test_refs=("tests/test_recursive_improvement.py",),
        metrics=("guardrail_regression_rate", "cost_per_verified_improvement"),
        rationale="Reject single-metric optimization that trades correctness, trust, security, maintainability, latency, or cost for a superficial win.",
    ),
    ClaimSpec(
        "CLM-072",
        ("SRC-020",),
        "Diminishing returns, repeated sub-noise improvements, or exhausted experiment budgets must trigger deterministic retest, discard, or stop verdicts",
        "stopping_rules",
        disposition=Disposition.ADAPT,
        burden=BurdenOfProof.IMPLEMENT,
        state=ImplementationState.IMPLEMENTED,
        section="control-plane",
        code_refs=("src/hive_mind_os/recursive_improvement.py",),
        test_refs=("tests/test_recursive_improvement.py",),
        metrics=("wasted_experiment_rate", "marginal_value_per_compute", "stop_rule_compliance"),
        rationale="Convert diminishing returns into explicit patience and experiment-budget boundaries so autonomy cannot justify endless low-value iteration.",
    ),
    ClaimSpec(
        "CLM-073",
        ("SRC-020",),
        "Strong recursive self-improvement involving self-weight modification, mission mutation, policy mutation, concealed capability growth, replication, or autonomous resource acquisition is outside governed authority and must remain prohibited or separately proven under the highest safety burden",
        "strong_rsi_boundary",
        disposition=Disposition.ADAPT,
        section="constitutional-and-court-governance",
        metrics=("forbidden_recursive_action_rate=0",),
        rationale="Preserve the distinction between evidence-backed weak RSI and speculative strong RSI; capability growth cannot expand authority or rewrite the constitution.",
    ),
)
