"""Quarantined additive Phase 2 contracts; not selected by the runtime champion."""

from .contracts import (
    AttemptKind,
    CostObservation,
    MemoryDisposition,
    MemoryRecord,
    MemoryRelation,
    NativeUsageField,
    NormalizedUsageDimension,
    ReconciliationStatus,
    RepositoryIdentity,
    RetentionClass,
    Sensitivity,
    UsageAxis,
    UsageEvent,
    UsageOutcome,
    UsagePurpose,
    canonical_json,
    contract_digest,
)
from .store import (
    STORE_APPLICATION_ID,
    STORE_SCHEMA_VERSION,
    DeliveryConflictError,
    DuplicateRecordError,
    FoundationStore,
    FoundationStoreError,
    IntegrityReport,
    OutboxMessage,
    RepositoryConflictError,
    ScopeViolationError,
    StoreVersionError,
)

CANDIDATE_STATUS = "quarantined"
RUNTIME_ACTIVATED = False

__all__ = [
    "AttemptKind",
    "CANDIDATE_STATUS",
    "CostObservation",
    "DeliveryConflictError",
    "DuplicateRecordError",
    "FoundationStore",
    "FoundationStoreError",
    "IntegrityReport",
    "MemoryDisposition",
    "MemoryRecord",
    "MemoryRelation",
    "NativeUsageField",
    "NormalizedUsageDimension",
    "OutboxMessage",
    "RUNTIME_ACTIVATED",
    "ReconciliationStatus",
    "RepositoryConflictError",
    "RepositoryIdentity",
    "RetentionClass",
    "STORE_APPLICATION_ID",
    "STORE_SCHEMA_VERSION",
    "ScopeViolationError",
    "Sensitivity",
    "StoreVersionError",
    "UsageAxis",
    "UsageEvent",
    "UsageOutcome",
    "UsagePurpose",
    "canonical_json",
    "contract_digest",
]
